### ISSUE TITLE
User could not attach screenshots to email when trying to share

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/ScreenshotGo#107]
Prerequisite:
Existing collections with screenshots

STR:

1. Launch Scryer
2. Tap a collection
3. Long press a shot
4. Choose share, then choose email

Expected result:
User should be able to share via email attachment

Actual result:
Gmail will not allow empty attachment

Reproduce Rate: 100%

Device: Nexus 5
Scryer Ver.: 1.0(202).nightly
Android Ver.: 6.0.1
WebView: 68.0.3440.91

Clip:
https://drive.google.com/open?id=1psp57sLoggwGVv3x1jvQvfp8v8r0M5rC

**Comment by mlwang32** [comment]
User can share photos and screenshots via email by using Gallery on Nexus 5

**Comment by benjamin-cheng** [comment]
Reference to the wrong issue, reopen it!

**Comment by weslyhuang** [comment]
should it be a P0 issue?

**Comment by weslyhuang** [comment]
P0 per discussion after standup.

**Comment by benjamin-cheng** [comment]
Ask @cynthiatang 's help for more detail steps since I am not able to reproduce this issue.

**Comment by mlwang32** [comment]
Just tested on Nexus 5 (Android 6.0.1) using v. 1.0(333), still got the same result.

**Comment by cynthiatang** [comment]
Note: This issue cannot be reproduced in Oppo, Vivi, Samsung J7, Pixel2.
