### ISSUE TITLE
Enable/integrate Adjust

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/ScreenshotGo#111]
to enable adjust for ScreenshotGo, Dev. will need a token with the right package name from Marketing.

**Comment by mxlius** [comment]
@elin-moco "org.mozilla.scryer"

**Comment by weslyhuang** [comment]
1. MKT: generate token of ScreenshotGo
2. DEV: integrate/enable Adjust in ScreenshotGo

**Comment by weslyhuang** [comment]
we'll need to triage it's priority, e.g., blocking open beta or official release?

**Comment by weslyhuang** [comment]
Per discussion, bring this back to P0, but this one will be a lower priority among P0s. (lower than fixing the other P0s, and enable stability test).

**Comment by elin-moco** [comment]
I've sent the integration details to max, let me know if anyone need anything else.

**Comment by weslyhuang** [comment]
Product support to prioritize Firebase integration over Adjust. thus downgrade this to be P1.

**Comment by weslyhuang** [comment]
add "need help" to flag it as higher P1.

**Comment by weslyhuang** [comment]
integrated thus close it.
