### ISSUE TITLE
After allowing or denying the permission, the on-boarding page doesn't disappear

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/ScreenshotGo#115]
Prerequisite:
N/A

STR:
1. Launch Scryer for the first time
2. Tap LET'S LOAD IT!
3. Tap DENY on storage permission prompt

Expected result:
Error page should be displayed

Actual result:
Nothing happens after the first tap, second tap will take user to the error page

Reproduce Rate: 100%

Device: Nexus 5
Scryer Ver.: 1.0(202).nightly
Android Ver.: 6.0.1
WebView: 68.0.3440.9

Clip:
https://drive.google.com/open?id=1t0cUS8-ZV-i3sTcMHYggNYBgoeoQS0NE

**Comment by cynthiatang** [comment]
https://drive.google.com/open?id=1429_053OW-oqkk8kXoLpkeehQF4UlNrU

**Comment by weslyhuang** [comment]
doubt if this issue still exists as we've modified some flow about this. QAwanted.

**Comment by witsmo** [comment]
Verify on ScreenshootGo 1.0(788).nightly
Device: Nexus 5
OS: Android 6.0.1
Result: 1st deny and 2nd deny different result

Device: Advan i5C
OS: Android 5.1
Result: No permission request
