### ISSUE TITLE
Dialog padding should be smaller 

### ISSUE THREAD

**Issue by fangshih** [mozilla-tw/ScreenshotGo#132]
All the dialogs left, and right padding should be 40dp. Thanks!!

![screen shot 2018-09-11 at 2 48 16 pm](https://user-images.githubusercontent.com/4862573/45343003-2b5bdb80-b5d2-11e8-95c1-cb57da4a9d18.png)
Spec link
https://mozilla.invisionapp.com/share/CQNB9INNKDX#/313755895_4-4_Spec_SP_Settings_Spec

**Comment by weslyhuang** [comment]
S1 as spec compliance issue.

**Comment by weslyhuang** [comment]
system limitation unless make our own.
