### ISSUE TITLE
Update the link of "RATE ON GOOGLE PLAY"" (settings --> give feedback) to official Google Play Store page

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/ScreenshotGo#169]
Currently in Nightly builds the link leads users to our developer's own Google Play page. Not sure if this will be switched automatically in production builds, so submit an issue for the record.

**Comment by benjamin-cheng** [comment]
Yes, it would direct to the production google play store on release build. Follow the same mechanism as Rocket. I will try to verify it with release build when the google play store is ready.
