### ISSUE TITLE
Would be nice to back to the Detail view after users tried to reopen Scryer from home

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#170]
1. Launch Scryer
2. Tap a collection
3. View a shot in Detail View
4. Tap system Home key 
5. Open Scryer again

Expected Result 
 - Would be nice to back to the Detail view

Actual Result
 - It would back to the Collection view
 - Video https://drive.google.com/open?id=1VDCZYkIC3Nz3Cm_QY-O8kic2HLG5G0BE

Reproduce Rate: 10/10 

All devices
Scryer 294

**Comment by pharspher** [comment]
fix in #172

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixed 2
Android 8.1.0
ScreenshotGo 0.8(445)
