### ISSUE TITLE
Flashes when users tried to take a screenshot via FAB/GO button

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#174]
1. Launch Scryer
2. Tap FAB/GO button

Expected Result
 - Don't flash

Actual Result
 - Flashes
 - Video: https://drive.google.com/open?id=1sshgVt37SiLauNgVL90YyB9NNb0trfaV

Reproduce Rate: 5/5

Redmi 4A
Android 7.1.2
ScreenshotGo 1.0(320).nightly

Note: this issue cannot be reproduced in Pixel 2 with android 8

**Comment by weslyhuang** [comment]
seems also happens with my S8+ but hardly can see it. Maybe the level of impact is related to HW performance? Major visual impact = S2, maybe "NOT" critical enough to be P0?
