### ISSUE TITLE
The header is transparent and consists of back, share and overflow menu buttons in Detail View

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#176]
1. Launch Scryer
2. Tap a shot 

Expected 
 - The header is transparent and consists of back, share and overflow menu buttons (UX spec: 4.1A)
 -screenshot
<img width="270" alt="screen shot 2018-09-14 at 2 46 27" src="https://user-images.githubusercontent.com/12458450/45534455-bd135500-b82d-11e8-96ee-056a80127449.png">

Actual Result
 - No overflow menu button in Detail view
 - 
![screenshot_2018-09-14-14-41-18-206_gro allizom scryer](https://user-images.githubusercontent.com/12458450/45534437-acfb7580-b82d-11e8-816d-9e1a81d21c27.png)

Reproduce Rate: 10/10

Redmi 4A
Android 7.1.2
ScreenshotGo 1.0(320).nightly

**Comment by weslyhuang** [comment]
same with my Samsung S8+, android 8.0.0, build320.nightly. guess P1 would be enough?

**Comment by cynthiatang** [comment]
Verified: fixed

Pixel2
Android8.1.0
ScreenshotGo 1.0(346).nightly
