### ISSUE TITLE
Users cannot search the text with default browser when the default browser is Rocket (maybe Redmi 4A only)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#178]
1. Set Rocket as the default browser
2. Launch Scryer
3. Tap a shot 
4. Tap OCR
5. Long press selects the text 
6. Tap search icon 

Expected Result
 - Users would see an option named Rocket. It could direct users to the default browser and searches the text with default search engine

Actual Result 
 -  no Rocket 
 - https://drive.google.com/open?id=1PdoKBM9Q1Ggv4A1_F_rymfRlkx1DJc2b

Reproduce Rate: 10/10

Redmi 4A
Android 7.1.2
Scryer 1.0(320).nightly

Note: this issue cannot be reproduced in Pixel 2 with Android 8

**Comment by weslyhuang** [comment]
@ChenMorpheus you may want to take a look and help judge if we would like to update the design here? Thanks.

**Comment by weslyhuang** [comment]
the current design limitation. will be fixed by #448.

**Comment by witsmo** [comment]
Verify resolved on ScreenshootGo 1.0(767)
Device: Redmi 4A
OS: Android 7.1.2
