### ISSUE TITLE
It should show a snack bar "Copied" after copying selected text

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#182]
1. Launch Scryer
2. Tap a shot 
3. Tap OCR button
4. Long press selects the text 
5. Tap COPY

Expected Result:
 - Show snack bar message to indicate the text has been copied and unselect the text (UX spec: 4.2H)
 <img width="704" alt="screen shot 2018-09-14 at 5 29 51" src="https://user-images.githubusercontent.com/12458450/45542246-d4f5d380-b843-11e8-982c-c0f0aca5ad59.png">

Actual Result
 - It doesn't show the snack bar message
 - Video: https://drive.google.com/open?id=12fTr4-tzkIiHH1FQ8Wj7BAFBiMRjdzWQ

Reproduce Rate: 10/10

All devices
ScreenshotGo 1.0(320).nightly

**Comment by weslyhuang** [comment]
fixed by #483

**Comment by weslyhuang** [comment]
verified with Pixel XL, Android 9.
