### ISSUE TITLE
Don’t provide OCR feature when encountering a screenshot with special size

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#183]
1. Launch Rocket 
2. Visit bukalapak.com
3. Tap Rocket's screenshot button 
4. Launch Scryer 
5. Tap the shot that you just took via Rocket

Expected Result
 - Don’t provide OCR feature when encountering a screenshot with special size (UX spec: 4.2A)
<img width="371" alt="screen shot 2018-09-14 at 6 50 16" src="https://user-images.githubusercontent.com/12458450/45546669-8e5aa600-b850-11e8-8629-0c361ed33b70.png">

Actual Result
 - It provides OCR feature. 
 - Wait for UX team to provide the detail about  "special size"

All devices
ScreenshotsGo 1.0(320).nightly

**Comment by weslyhuang** [comment]
guessing we already plan to disable OCR for special-sized screenshot?

**Comment by pharspher** [comment]
#191 provides a solution that will show a toast to tell the user the recognition result may be worse on these kinds of images. (ref: UX spec 4.1)
