### ISSUE TITLE
It would show a message with 2 options "取消" and "Delete"

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#203]
(Issued by Chloe)

System Language: 中文
1. Launch Scryer
2. Long tap a screenshot
3. Tap Delete

Expected Result:
 - Show a message with 2 options "Cancel" and "Delete"

Actual Result:
 - Show a message with 2 options "取消" and "Delete"

Reproduced Rate: 10/10

Scryer 1.0(346).nightly

**Comment by weslyhuang** [comment]
Chloe uses Samsung device. I can repro it with my Samsung S8+ but issue disappeared when I changed the system language to English. So guess this is more like a Samsung issue.

**Comment by benjamin-cheng** [comment]
It's expected behavior since the `Cancel` is a system string and it has built-in translated string. If it's a issue impacted to our user, then we should avoid to use those system strings and pass to l10n team for translation.

**Comment by weslyhuang** [comment]
we may want to align the string usage in the future (assume people in ID may use Chinese UI?), P2.
