### ISSUE TITLE
Badge with "1" is shown in App icon in App icon after taking a screenshot via HW key

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#204]
(Issued by Wesly)
STR 
1. Screenshot via HW key

Expected Result
 - no change in App icon

Actual Result
 - badge with "1" is shown in App icon (until you dismiss the notification)
 - Video https://drive.google.com/open?id=16WIbOweSQbK6HKDzjHHw2wCCLIfibKIi

Samsung
Android 8.0.0
ScreenshotGO 346.nightly

**Comment by weslyhuang** [comment]
not necessarily a P0, but still confusing to me. (the counter is always 1 even I took more screenshots via HW key, and become zero when I dismiss the notification) Maybe we'll like to define the rule of indicators?

**Comment by weslyhuang** [comment]
also depends on each device's launcher design, we may like to enhance the design/icon badge/notification handling in the future.
