### ISSUE TITLE
Toast "Screenshot feature enabled / disabled" is confusing 

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/ScreenshotGo#208]
when I first saw it, I wasn't sure what does it mean screenshot feature? 
when i disable it from notification and the toast is showing over my other app, it is confusing where the msg is coming from. It should be coming from the action i just did (which is stop ScreenshotGo) but it's showing on top of other apps

https://drive.google.com/file/d/1BGzhccZPl-HPymXrFOHHeyZxGr57XCPy/view?usp=sharing

**Comment by ChenMorpheus** [comment]
Refer to #211 for the copy.  As for the snackbar/toast, it only prompts when you stop ScreenshotGo from the notification as a confirmation. If the implication is too vague, I think we could simply remove the toast.

**Comment by joechengla** [comment]
similar to my comments in another bug. "screenshot" is a generic term and feature that is not exclusive to us so the link to Firefox ScreenshotGo may not be strong

**Comment by weslyhuang** [comment]
guess it would be good to get some objective numbers for judgment (or check during user testing). don't seem like a P0 but let's triage it.

**Comment by weslyhuang** [comment]
P1 per triage.

**Comment by weslyhuang** [comment]
@ChenMorpheus pls help comment, tks.

**Comment by ChenMorpheus** [comment]
Based on the usability testing, none of the users were confused with the snack bar. But we'll keep monitoring the issue to ensure there is no confusion.

**Comment by weslyhuang** [comment]
close this and follow in #315
