### ISSUE TITLE
Share with friends message polish "It's call Firefox ScreenshotGo"

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/ScreenshotGo#209]
Low priority but "It's call Firefox ScreenshotGo" sounds a bit weird, IMO.

**Comment by ChenMorpheus** [comment]
@elin-moco @joechengla This string was from product marketing. What do you think?

**Comment by weslyhuang** [comment]
Marketing's call. P1.

**Comment by elin-moco** [comment]
@joechengla 
The string we provided are:

Hey, check out this new app that helps 
you organize and find your screenshots easily. 
It’s called Firefox ScreenshotGo.
https://mzl.la/xxxxxx

You mean the pronunciation of "It’s called Firefox ScreenshotGo." is weird?

**Comment by weslyhuang** [comment]
won't fix
