### ISSUE TITLE
Learn More Page for Send Usage Data needs update to include Firefox ScreenshotGo (Bug 1492407)

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/ScreenshotGo#210]

**Comment by joechengla** [comment]
https://support.mozilla.org/en-US/kb/send-usage-data-firefox-mobile-devices

**Comment by weslyhuang** [comment]
submitted https://bugzilla.mozilla.org/show_bug.cgi?id=1492407 for this.

**Comment by weslyhuang** [comment]
(add information from #273)

Open app > Settings > Send usage data > Learn more

"Screenshot Go" are not listed on this page yet, please use the latest one to update: https://docs.google.com/document/d/1X-16TX3zGYUVGSsvZsdKDdACUawD9vmaJBdWLyc2XlY/edit#heading=h.wcrl6mg5zckl

**Comment by weslyhuang** [comment]
done. ScreenshotGo included.

https://support.mozilla.org/en-US/kb/send-usage-data-firefox-mobile-devices

![included](https://user-images.githubusercontent.com/13250512/46187541-a7fef180-c316-11e8-93b7-0f7273df2dc2.png)
