### ISSUE TITLE
"Enable to take screenshots" is confusing

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/ScreenshotGo#211]
Enable "something" to take screenshots. IMO "something" is missing. It's like background service or something. 

https://drive.google.com/file/d/1bFM2P1KzQSyYdB0U9_5wanTO5cYGo3CB/view?usp=sharing
feels like a threat? we should make it sound more positive. I had no idea what this was until I tried it. 

Same for settings. No idea what "Enable to take screenshot" is until it is tried. If we really can't find a  copy that conveys the idea clearly, we should consider having some description 
https://drive.google.com/file/d/1ju5nihi1eiJuIEquAMectIRrZmNWNTVo/view?usp=sharing

**Comment by ChenMorpheus** [comment]
We had several rounds to discuss the precise name for the "something" with Firefox UX designers and copywriter, and the conclusion was that we decided to skip the term and only focused on the outcome of the switch itself.  

![](https://user-images.githubusercontent.com/18019946/45408016-b3f37e00-b69d-11e8-82df-ad733abe65d9.png)

> https://drive.google.com/file/d/1bFM2P1KzQSyYdB0U9_5wanTO5cYGo3CB/view?usp=sharing
As for this screen, I've updated the copy to "enable screenshotGo to take screenshot" to make it more specific.

**Comment by joechengla** [comment]
the confusion is that i know i can take screenshots even if i don't enable it because screenshot is a generic action that's offered by the system and not exclusive to us so from the description, i have no idea what benefit i get for enabling. so i think there's room for improvement here 

let's pay attention to this during usability testing or we can even A/B test the strings and see how the engagement differs

**Comment by weslyhuang** [comment]
don't sound like a P0, let's triage it soon.

**Comment by weslyhuang** [comment]
something to test while user testing, P1.

**Comment by ChenMorpheus** [comment]
Please refer to #313 for more details.

**Comment by weslyhuang** [comment]
closed this and follow the new design in #313.
