### ISSUE TITLE
In Settings, prompt to save? or to sort / organize...?

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/ScreenshotGo#221]
to sort or organize seems to match to action that I will be doing more. 
the screenshot is saved regardless of whether the prompt shows or not

**Comment by weslyhuang** [comment]
ni @ChenMorpheus for comment

**Comment by weslyhuang** [comment]
something to test while user testing, P1.

**Comment by weslyhuang** [comment]
fixed, to be verify.

**Comment by cynthiatang** [comment]
Verified: Fixed

Tap to Sort screenshots

ScreenshotGo 1.0(505).nightly
Sony Z3C
Android 6.0.1
