### ISSUE TITLE
tap to sort notification isn't working

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/ScreenshotGo#223]
once i tap it and is taken to the screenshotgo app, nothing happens 
build (370)

**Comment by weslyhuang** [comment]
quite basic but I've never met this. @joechengla what's your device and OS version?

**Comment by weslyhuang** [comment]
I misunderstood the scenario, the flow isn't ready (out of scope of MVP) but per triage we'll add this for open beta so P0.

**Comment by cynthiatang** [comment]
Verified: Fixed

ScreenshotGo 1.0(430).nightly
Pixel2
Android 8.1.0
