### ISSUE TITLE
No feedback when creating a new category when managing unsorted screenshots

### ISSUE THREAD

**Issue by harly21** [mozilla-tw/ScreenshotGo#224]
STR: 
1. Tap unsorted collection
2. Tap "Sort" button on the action bar
3. Tap "CREATE NEW", type in a collection name and tap ADD

Expected result:
A banner or some sort of feedback to let the user know that the screenshot has been added to the newly created collection

Actual result:
Display the next image

**Comment by weslyhuang** [comment]
tried the issue and indeed there is inconsistency. case (a) will show a snack bar but (b) and (c) will not.

a. FAB to screenshot --> create a new collection for the screenshot
b. HW key to screenshot --> tab notification to sort --> create a new collection for the screenshot
c. (Harly's case above) sort screenshot from unsorted --> create a new collection for the screenshot

ni @ChenMorpheus for comment first.

**Comment by weslyhuang** [comment]
confirmed will add the same snack bar to case b & c.

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixed 2
Android 8.1.0
ScreenshotGo 0.8(445)
