### ISSUE TITLE
Integrate Firebase

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/ScreenshotGo#233]
learned we haven't done that so submit an issue for tracking. should be something to include before official launch so P1.

**Comment by weslyhuang** [comment]
what we have already: ML kit related.
what we don't have yet: crashlytics, analytics

**Comment by weslyhuang** [comment]
per discussion, this is the "highest P1"="the lowest P0" that we'd like to have in open beta, if feasible.

**Comment by chloechen1122** [comment]
I would recommend that place higher priority on Firebase integration for our beta launch.

**Comment by weslyhuang** [comment]
per discussion this one is over Adjust so a normal P0, not lowest P0 anymore.

**Comment by weslyhuang** [comment]
Roger is working on it.

**Comment by weslyhuang** [comment]
confirmed crashlitics enabled.
