### ISSUE TITLE
Weird image size 

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/ScreenshotGo#236]
Weird sounds very casual in verbal conversational English 
Suggest using other terms.

**Comment by weslyhuang** [comment]
ni @ChenMorpheus for comment.

**Comment by joechengla** [comment]
this is when doing OCR with large sized images

**Comment by weslyhuang** [comment]
l10n ongoing. it's the debug message Joe was seeing currently.

**Comment by cynthiatang** [comment]
Verified: Fixed

ScreenshotGo 1.0(430).nightly
Pixel2
Android 8.1.0
