### ISSUE TITLE
Failed to take a screenshot of the entire screen on WhatsApp video calls 

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#239]
Enable FAB

1. Use WhatsApp to make a video calls
2. Tap FAB to take a screenshot 

Expected Result:
 - Users can take a screenshot of the entire screen on WhatsApp video calls 

Actual Result:
 - User cannot take a screenshot of the entire screen on WhatsApp video calls 
![screenshot_1537723319340](https://user-images.githubusercontent.com/12458450/45947496-0f6f2580-c027-11e8-8635-eb428f270123.jpg)

Pixel2
ScreenshotGo 1.0(407).nightly

**Comment by weslyhuang** [comment]
potential competitor can do it, pls help check our permission setting during the test, tks.

**Comment by chloechen1122** [comment]
We can hold its permissions, just need to be careful about the information security.

**Comment by weslyhuang** [comment]
down to P2 per discussion, seems not the common scenario for our users.
