### ISSUE TITLE
It would take black screenshots (App: YoutubeGo, Hago)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#240]
It would take a black screenshots
<img width="854" alt="screen shot 2018-09-25 at 9 18 54" src="https://user-images.githubusercontent.com/12458450/45987498-5ea76b80-c0a4-11e8-98f6-1820824d70a9.png">
<img width="675" alt="screen shot 2018-09-25 at 9 18 42" src="https://user-images.githubusercontent.com/12458450/45987499-5ea76b80-c0a4-11e8-8140-2c797ed56012.png">
<img width="670" alt="screen shot 2018-09-25 at 9 18 13" src="https://user-images.githubusercontent.com/12458450/45987500-5ea76b80-c0a4-11e8-9fcc-a0ab1d155261.png">

Pixel 2
Android 8.1.0
ScreenshotGo 1.0(407).nightly

**Comment by chloechen1122** [comment]
We can hold its permissions, just need to be careful about the information security.

**Comment by benjamin-cheng** [comment]
Fix this issue by keeping capture permission intent.

**Comment by vanceyen** [comment]
Verified fixed : version build 588
