### ISSUE TITLE
Unable to take a screenshot of the playing video (App: SHAREit, Instagram, UC Browser)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#241]
<img width="762" alt="screen shot 2018-09-25 at 9 33 15" src="https://user-images.githubusercontent.com/12458450/45987811-21dc7400-c0a6-11e8-9089-2ab54031abe3.png">

<img width="841" alt="screen shot 2018-09-25 at 9 33 04" src="https://user-images.githubusercontent.com/12458450/45987813-21dc7400-c0a6-11e8-9df8-118c829163b6.png">

<img width="759" alt="screen shot 2018-09-25 at 9 32 51" src="https://user-images.githubusercontent.com/12458450/45987815-22750a80-c0a6-11e8-9e22-91dfb79c6213.png">

<img width="733" alt="screen shot 2018-09-25 at 9 32 41" src="https://user-images.githubusercontent.com/12458450/45987843-433d6000-c0a6-11e8-8b1f-15599de0b7ea.png">

Pixel2
Android 8.1.0
ScreenshotGo 1.0(407).nightly

**Comment by weslyhuang** [comment]
@cynthiatang can our "potential" competitor (the other screenshot App you tried) do this? tks

**Comment by benjamin-cheng** [comment]
Fix this issue by keeping permission intent.

**Comment by vanceyen** [comment]
verified fixed : version build 588
