### ISSUE TITLE
The header and FAB should disappear during OCR recognizing process

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#242]
1. Launch Scryer
2. Tap a shot 
3. Tap OCR

Expected Result
 - The header and FAB should disappear during OCR recognizing process
<img width="284" alt="screen shot 2018-09-25 at 10 08 05" src="https://user-images.githubusercontent.com/12458450/45988733-02941580-c0ab-11e8-9662-6e94c33d2373.png">

Actual Result
 - The header and FAB do not disappear
 - Video https://drive.google.com/open?id=1unoW1UaTVvl5Qw2rLyRwrHfc1bgFyVmz

Pixel2 
ScreenshotGo 1.0(407).nightly

**Comment by weslyhuang** [comment]
doubt if this issue still exists as we've modified some flow about this. QAwanted.

**Comment by witsmo** [comment]
Verify resolved on ScreenshootGo 1.0(788).nightly
Device: Nexus 5
OS: Android 6.0.1
