### ISSUE TITLE
Enable Go btn dialogue appears with scrambled string after user switching the screenshot service off and on on settings page 

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/ScreenshotGo#247]
Precondition:
Screenshot service enabled
Go button enabled

STR:
1. Go to settings
2. Expand notification, tap stop -> screenshot service button is off
3. Switch the screenshot service back on
4. Go back to Scryer home by tapping the app back button

Expected result:
Nothing happens

Actual result: 
'Enable GO button to take screenshots?" dialogue reappears, with scrambled string

Scryer version and Device:
v1.0(408).nightly
Device: Nexus 5
WebView: 69.0.3497.100
Android 6.0.1 

Screenshot:
![20180925-scryerstring](https://user-images.githubusercontent.com/746727/45996881-6250e780-c0d0-11e8-8879-03293ffef2a6.png)

Clip:
https://drive.google.com/open?id=1sPjZ8QQ6y8KPFd_w2cMmkUqM7ArLDiTG

**Comment by weslyhuang** [comment]
need to triage:
1. %1$s seems like an easy to fix, and P0 to me
2. unsure about the dialogue, expected or not? easy to fix in time?

**Comment by cynthiatang** [comment]
Verified: Fixed

Nexus 5
Android 6
ScreenshotGo 0.8(445)
