### ISSUE TITLE
 It won't show the notification "Tap to sort screenshots" on some devices when using HW key to take a screenshot

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#256]
1. Launch ScreenshotGo
2. Go to Settings -> Enable to take screenshots
3. Take a screenshot via the Hardware key

Expected Result
 - Show the notification "Tap to sort screenshots" (UX spec 1.2 B)

Actual Result
 - It won't show the notification on some devices. 

Screenshot 1.0(408)
Redmi 4A
Oppo A371

**Comment by weslyhuang** [comment]
need to check more about the devices config.

**Comment by weslyhuang** [comment]
seems nonactionable?
