### ISSUE TITLE
Don't show a notification when opening the app "Photo" 

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#263]
1. Tap FAB
2. Open the app named "Photos"

Expected Result
 - Don't show a notification "Tap to sort screenshots"
 - Only show a notification "Tap to sort screenshots" when taking a screenshot via HW key

Actual Result 
 - Show a notification "Tap to sort screenshots"
 - Video: https://drive.google.com/open?id=1DNgSLhe4dvE6f_o_5-OrYJkQfyaMlo9H

Pixel 2 
Android 8.1.0
ScreenshotGo 1.0(430).nightly

**Comment by weslyhuang** [comment]
stay in P1, need to monitoring user feedback/data.
