### ISSUE TITLE
Telemery data review

### ISSUE THREAD

**Issue by benjamin-cheng** [mozilla-tw/ScreenshotGo#266]

**Comment by cnevinc** [comment]
I just found this when I see those pings. This one is something we should bring up in the review
https://github.com/mozilla-tw/ScreenshotGo/blob/eab9166168973280edfc0d8362feeba313cfec3f/app/src/main/java/org/mozilla/scryer/telemetry/TelemetryWrapper.kt#L198

**Comment by cnevinc** [comment]
I just found this when I see those pings. This one is something we should bring up in the review
https://github.com/mozilla-tw/ScreenshotGo/blob/eab9166168973280edfc0d8362feeba313cfec3f/app/src/main/java/org/mozilla/scryer/telemetry/TelemetryWrapper.kt#L198

**Comment by cnevinc** [comment]
I just found this when I see those pings. This one is something we should bring up in the review
https://github.com/mozilla-tw/ScreenshotGo/blob/eab9166168973280edfc0d8362feeba313cfec3f/app/src/main/java/org/mozilla/scryer/telemetry/TelemetryWrapper.kt#L198

**Comment by cnevinc** [comment]
Is there a deadline for data review? Thank you!

**Comment by weslyhuang** [comment]
we need to complete the review before making the App official (currently beta), and since we don't have a clear timeline for official today, I think it's valid to set a target as 2018 Dec. 31, the end of this year. 

@chloechen1122 once we have a date for official please also share here. tks.
