### ISSUE TITLE
The on-boarding page layout would be wrong when the text size is larger  

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#267]
(Issued by Morpheus)

System Font: Text size = XXL 
 
1.  Install ScreenshotGo
2. Launch ScreenshotGo 

<img src="https://user-images.githubusercontent.com/12458450/46071826-7b7e9480-c1b3-11e8-8983-8cdbcf29ceeb.png"  height="30%" width="30%"> <img src="https://user-images.githubusercontent.com/12458450/46071831-7e798500-c1b3-11e8-822e-d102e7d66e23.png"  height="30%" width="30%"> <img src="https://user-images.githubusercontent.com/12458450/46071837-846f6600-c1b3-11e8-9d09-358266952768.png"  height="30%" width="30%">

**Comment by cynthiatang** [comment]
<img src="https://user-images.githubusercontent.com/12458450/46072749-b5e93100-c1b5-11e8-816c-e91904815665.png"  height="30%" width="30%"> <img src="https://user-images.githubusercontent.com/12458450/46072754-b84b8b00-c1b5-11e8-93a3-5a791debc4a8.png"  height="30%" width="30%"> <img src="https://user-images.githubusercontent.com/12458450/46072760-bb467b80-c1b5-11e8-8a4a-f1ca3cef8da3.png"  height="30%" width="30%">

**Comment by weslyhuang** [comment]
P0 first and to have a quick investigation/discussion with UX, to decide if anything we can improve today. (rest will be P1 and overall prioritized for the official launch.

**Comment by cynthiatang** [comment]
Verified: Fixed 

Pixel2
Android 8.1.0
ScreenshotGo 0.8(469).debug
