### ISSUE TITLE
It should check if there are any unsorted screenshots 

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#268]
Disable Prompt to sort

1. Take a screenshot via FAB
2. Launch ScreenshotGo 

Expected 
 - It should check if there are any unsorted screenshots 

Actual
https://drive.google.com/open?id=19VeDtdZVCCZEgoHrLBWY1f3gmDYeyZK1

**Comment by weslyhuang** [comment]
P0 first and to have a quick investigation/discussion with UX, to decide if anything we can improve today. (the rest will be P1 and overall prioritized for the official launch.)

**Comment by weslyhuang** [comment]
UX to comment the decision here, then close. @ChenMorpheus

**Comment by ChenMorpheus** [comment]
I've updated the spec for unsorted prompt rule when disabling “prompt to sort” according to tech limits.
![image](https://user-images.githubusercontent.com/18019946/46185772-fbb90d00-c30d-11e8-836d-162d93545d1a.png)
