### ISSUE TITLE
It would prompt a strange capturing permission on user's Oppo device

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#271]
(Issued by Morpheus)

It would prompt a strange capturing permission on user's Oppo device

User's Oppo device   v.s.   our Oppo device A371
<img width="1004" alt="screen shot 2018-09-27 at 11 22 20" src="https://user-images.githubusercontent.com/12458450/46121939-bbdc2200-c248-11e8-8b17-96ab1a48331d.png">

**Comment by weslyhuang** [comment]
might P2 in the future. keep monitoring user feedback/data.
