### ISSUE TITLE
Update “Send usage data” page

### ISSUE THREAD

**Issue by chloechen1122** [mozilla-tw/ScreenshotGo#273]
Open app > Settings > Send usage data > Learn more

"Screenshot Go" are not listed on this page yet, please use the latest one to update: https://docs.google.com/document/d/1X-16TX3zGYUVGSsvZsdKDdACUawD9vmaJBdWLyc2XlY/edit#heading=h.wcrl6mg5zckl

**Comment by weslyhuang** [comment]
It's tracked here too: https://bugzilla.mozilla.org/show_bug.cgi?id=1492407

**Comment by weslyhuang** [comment]
checked again and confirmed dup to #210, thus close this one.
