### ISSUE TITLE
On settings page, tapping give feedback and rate 5 stars will lead to empty google play page

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/ScreenshotGo#275]
STR
1. Launch Scryer
2. Tap Menu -> Settings -> Give feedback
3. Tap Yes, Rate 5 Stars

Expected result:
Leads to a google play page to rate the app

Actual result:
Leads to item not found page

ScreenshotGo version:
v0.8(445)

Device: Redmi 4X
Android 7.1.2

Screenshot:
![screenshotgonorate](https://user-images.githubusercontent.com/746727/46129039-01f4ae00-c268-11e8-9392-d640f2954d96.png)

**Comment by cynthiatang** [comment]
@mlwang32 could you please verify it again? It should work now

**Comment by weslyhuang** [comment]
btw need to join the beta testing in advance so you can see the page.

**Comment by mlwang32** [comment]
works for version 1.0(454).nightly installed from google play store, device: Redmi 4X, Android 7.1.2

**Comment by weslyhuang** [comment]
verified as comment above.
