### ISSUE TITLE
The link used to share with friends does not lead to a functional page

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/ScreenshotGo#276]
STR:
1. Launch Scryer
2. Tap Menu -> Settings -> Share with friend
3. Tap mail
4. Send the mail 

Expected result:
Email will contain a link to the app download page

Actual result:
Link sent via email is not functional (URL not found): [https://mzl.la/2NMgD30](url)

ScreenshotGo version:
v0.8(445)

Device: Redmi 4X
Android 7.1.2

Screenshot:
![issue](https://user-images.githubusercontent.com/746727/46129898-8ba57b00-c26a-11e8-88b5-0fdbe457da7c.png)

**Comment by cynthiatang** [comment]
dup to #270
