### ISSUE TITLE
Under about, tapping privacy notice does not lead to ScreenshotGo privacy page

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/ScreenshotGo#277]
STR:

1. Launch Scryer
2. Tap Menu -> Settings -> About - 
3. Check Privacy Notice : The content should be correct

Expected result:
Page should display privacy notice

Actual result:
Seems like a default wrong URL page

ScreenshotGo version:
v0.8(445)

Device: Redmi 4X
Android 7.1.2

Screenshot:
![screenshotgonoprivacy](https://user-images.githubusercontent.com/746727/46130448-e9869280-c26b-11e8-8ec5-5e2c300ec027.png)

**Comment by weslyhuang** [comment]
content ready, to be published on Sep. 28 US time when open beta is released.

**Comment by weslyhuang** [comment]
content published, resolved. (yet the logo is wrong and being trakced elsewhere. (https://bugzilla.mozilla.org/show_bug.cgi?id=1487436)

**Comment by cynthiatang** [comment]
Verified: Fixed

ScreenshotGo 1.0(505).nightly
Sony Z3C
Android 6.0.1
