### ISSUE TITLE
Update "About / Privacy Notice"

### ISSUE THREAD

**Issue by chloechen1122** [mozilla-tw/ScreenshotGo#278]
Update the About/Rights for both ScreenshotGo and Rocket with sentence on Firebase: https://docs.google.com/document/d/1QMnw09YXCIHLlo-BtFiJ7S5YvdlX6Uz2UJuKE1I3ovE/edit

**Comment by weslyhuang** [comment]
not really a P0, but will be good to update this for open beta.
