### ISSUE TITLE
User cannot tap search icon or search field on app home

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/ScreenshotGo#279]
Precondition:
First time use

STR:
1. Install ScreenshotGo app
2. Launch app
3. Tap 'Let's Go'
4. Tap 'Allow' on storage permission dialogue
5. Tap 'Later' on FAB permission prompt
6. Tap search icon or search field

Expected result:
Lead to search onboarding page

Actual result:
No action

ScreenshotGo version:
v0.8(445)

Device: Redmi 4X
Android 7.1.2

Clip:
https://drive.google.com/open?id=1e6OOn13CkTa0PJbrXGHfS1Bt0wqLBwM3

**Comment by cynthiatang** [comment]
This issue can be reproduced on Pixel 2  with Android 8.1.0

**Comment by cynthiatang** [comment]
Verified: Fixed 

Pixel2
Android 8.1.0
ScreenshotGo 0.8(469).debug
