### ISSUE TITLE
l10n version of "Your Rights"

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/ScreenshotGo#282]
Before the official launch, we should also include this (static page) in the product and connect it to pontoon (even Legal will take care of the translation)

The content is there:
https://github.com/mozilla/legal-docs/tree/master/firefox_screenshotgo_about_rights

**Comment by weslyhuang** [comment]
per discussion just made we'll embed the l10n version in code first, and deal with the maintenance work (e.g., link to Ponton, or a separate XML file, to be discussed) in the future. (maybe file a separate issue to track this?)

**Comment by benjamin-cheng** [comment]
#280

**Comment by weslyhuang** [comment]
Thanks! per Legal we should follow the Gdoc version[1], and I also submitted an issue[2] for github legal doc update.

[1] https://docs.google.com/document/d/1QMnw09YXCIHLlo-BtFiJ7S5YvdlX6Uz2UJuKE1I3ovE/edit
[2] https://github.com/mozilla/legal-docs/issues/1175
