### ISSUE TITLE
Must resolve for Google feature consideration

### ISSUE THREAD

**Issue by chloechen1122** [mozilla-tw/ScreenshotGo#290]
Some feedback from Google team for Rocket, and we also should take into account at this point:

1. Please only show the app settings button after the user has set “Don’t ask again”. If the user has not set the permission to “Don’t ask again”, instead of taking the user to the settings, have the button request the permission again. For more info: https://material.io/design/platform-guidance/android-permissions.html#denied-permissions)
(https://github.com/mozilla-tw/Rocket/issues/2692)

2. Manipulating ratings in the Google Play Store is against store policy. For more info: https://play.google.com/about/storelisting-promotional/ratings-reviews-installs/
(https://github.com/mozilla-tw/Rocket/issues/2693)

3. The app should not be directing users away from the Play Store based on their response to an in-app "Rate Us" or "5-star" pop-up. Some users may perceive this practice as misleading or deceptive.  Instead, there should be two distinct options such as Rate Us and Leave Feedback, giving the option directly to users.

![pasted image 0](https://user-images.githubusercontent.com/43133942/46191355-c3272c80-c329-11e8-8068-01bf66277e25.png)

**Comment by weslyhuang** [comment]
we'll need UX & Product to break down this into some UX design changes (and maybe issues too) to track.

**Comment by ChenMorpheus** [comment]
@chloechen1122 @joechengla We updated our copy to follow Rocket to redirect users based on their responses. According to Google's feedback, I'll revert to the original copy, "Rate on Google Play" and "Give us feedback." Please update the feedback survey accordingly since the feedback survey tended to only focus on the dissatisfied users.

**Comment by chloechen1122** [comment]
We'll keep the current version until we need to get featured by the play store, thanks.

**Comment by weslyhuang** [comment]
let's triage this again, maybe P2 or feature-backlog?

**Comment by weslyhuang** [comment]
remove P0 first to make the issue stats correct.
