### ISSUE TITLE
User feedback: When i want to capture screen in the bottom, it automaticly scroll up and i can't capture that information in the bottom

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/ScreenshotGo#301]
When i want to capture screen in the bottom, it automaticly scroll up and i can't capture that information in the bottom, please fix it

**Comment by weslyhuang** [comment]
need to know the App be using and also the device.

**Comment by weslyhuang** [comment]
The device used for commenting on GooglePlay: KEYone (bbb100)
Spec: https://blackberrymobile.com/specifications/keyone/

**Comment by weslyhuang** [comment]
not seen in our test, asked the user in GooglePlay and no feedback yet, non-actionable until then. keep monitoring.

**Comment by weslyhuang** [comment]
asked in GooglePlay but no user feedback yet, keep monitoring for 2 weeks (until Oct. 22) before closing it.

**Comment by weslyhuang** [comment]
close it for now as no feedback for 2 weeks.
