### ISSUE TITLE
User feedback: Doesn't show anything after i take a screenshot

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/ScreenshotGo#307]
Doesn't show anything after i take a screenshot

**Comment by weslyhuang** [comment]
the device posted this comment: Moto G (5S) Plus (sanders_n), Android 7.1.

**Comment by weslyhuang** [comment]
FAB or HW key?
what you expect to show?
App you are using?

**Comment by weslyhuang** [comment]
asked for more detail via GooglePlay console. monitoring.

**Comment by weslyhuang** [comment]
no feedback, down to P2 and monitor for 2 weeks before close it.

**Comment by weslyhuang** [comment]
closed on Oct. 23.
