### ISSUE TITLE
Proposal: New Telemetry Event Structure for ScreenshotGo

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/ScreenshotGo#308]
# Problem
- Prevent duplicate events: Using category+method+ojbect to specify an event makes this check hard.
- Reduce maintenance effort: Mapping events to Firebase and Amplitude is time-consuming. Using the Single key to specify an event is more easy to maintain.
- Identify the event is hard: Sometimes it's hard to understand the timing/location of the event from current structure.

# Effort:
- Needs to modify the pings we are using. (~30 methods for now) before GA (11/1)

# Cons:
- Grouping events will be hard when making a report. We need to group events manually instead of just say where object = "menu"
- Old queries like "DAU per feature" will need to be re-written

# Proposed structure:
- Category: This will be the event's key (identifier, < 30 chars )
- Method: This will be the version of the events(1,2..etc, < 20 chars )
- Object: This will be a string constant. ( e.g. go, < 20 chars )
- Value: This will be the event's value (< 80 chars )
- Extra : This is the same, Firebase call this "event parameters", Amplitude all this "event properties". This field only store data that 1. Nice to have 2. Won't be treated as an identifier to the event 3. additional info about this event, so it won't affect on the correctness of the report.

**Comment by weslyhuang** [comment]
could be a MUST before go ping to roduction.
