### ISSUE TITLE
Telemetry event data missing

### ISSUE THREAD

**Issue by elin-moco** [mozilla-tw/ScreenshotGo#311]
https://sql.telemetry.mozilla.org/queries/58744#153522
We just gone through the telemetry dashboard,
found that there are some data missing:
 - Collection name of click home_collections event
 - Search not interested still not found
 - Sorting panel need to distinguish multiple/single

**Comment by weslyhuang** [comment]
probably a P0, to be triaged.

**Comment by benjamin-cheng** [comment]
https://docs.google.com/spreadsheets/d/14zMWaUg6NJvpq5lP1O3qWaYE5PKMWEg-8TthV0Pfc5g/edit#gid=0
