### ISSUE TITLE
[Feature] Allow users to long press to multi-select

### ISSUE THREAD

**Issue by ChenMorpheus** [mozilla-tw/ScreenshotGo#312]
Based on the [usability testing result](https://docs.google.com/presentation/d/1LJj-feNK0oSfPzHCT9tmG7fr2yIUHLUotox10KcO2Zc/edit#slide=id.g43942815f9_1_58), "multi-select" played an essential role in the daily use. Please find [3.4 Multi-select](https://mozilla.invisionapp.com/share/24N3MMQB986#/324199836_3-4_Multi-Select) and 3.1B for related changes in the UX spec. 

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/18019946/46996402-18977200-d14f-11e8-8ed0-13a3a4204a53.png">

**Comment by fangshih** [comment]
<img width="1241" alt="screen shot 2018-10-17 at 4 49 22 pm" src="https://user-images.githubusercontent.com/4862573/47074316-c2006580-d22c-11e8-861c-2b1637b3c2e7.png">

**Visual Spec**
https://mozilla.invisionapp.com/share/CQNB9INNKDX#/326034545_10-1_Spec_SP_Multi_Select
**icon assets** 
https://drive.google.com/drive/u/2/folders/1aH8AmNybWFrWFwEHDJ7q169tGsXRf6mL

**Comment by weslyhuang** [comment]
implemented and released with build 651.
