### ISSUE TITLE
[Revision] Redesign the screenshot options in Settings

### ISSUE THREAD

**Issue by ChenMorpheus** [mozilla-tw/ScreenshotGo#313]
Based on the [usability testing result](https://docs.google.com/presentation/d/1LJj-feNK0oSfPzHCT9tmG7fr2yIUHLUotox10KcO2Zc/edit#slide=id.g43942815f9_1_44), copy for options in Settings and several actions were unclear. Please find [1.4 ABC](https://mozilla.invisionapp.com/share/24N3MMQB986#/310133912_1-4_Enable-Disable_Capturing) and [6.1](https://mozilla.invisionapp.com/share/24N3MMQB986#/310133927_6-1_Settings) for updates, thanks. 

<img width="1422" alt="image" src="https://user-images.githubusercontent.com/18019946/46991951-8ab18c00-d13a-11e8-9e95-6baaad9fefe4.png">

**Comment by fangshih** [comment]
For the visual design:
<img width="915" alt="screen shot 2018-10-16 at 2 30 01 pm" src="https://user-images.githubusercontent.com/4862573/46996648-0407a980-d150-11e8-9596-7421216d1099.png">

**You can see visual spec here**  
https://mozilla.invisionapp.com/share/CQNB9INNKDX

**Comment by weslyhuang** [comment]
no effect on build 603. @benjamin-cheng is patching it to release branch.

**Comment by weslyhuang** [comment]
verified on S8+ android 8 with build#606
