### ISSUE TITLE
[Revision] Updated the notification of hardware key detection

### ISSUE THREAD

**Issue by ChenMorpheus** [mozilla-tw/ScreenshotGo#314]
Since the notification of hardware key detection is pretty similar to the monitoring notification, I updated the UX spec based on material design. Please find [1.2 Add to collection via hardware key](https://mozilla.invisionapp.com/share/24N3MMQB986#/310133910_1-2_Add_To_Collection_With_Hardware_Key)

<img width="1699" alt="image" src="https://user-images.githubusercontent.com/18019946/46992425-9c942e80-d13c-11e8-9f0d-0719e41304b8.png">

**Comment by weslyhuang** [comment]
@ivantw08 would you help put a video on for reference? tks.

**Comment by weslyhuang** [comment]
1. I verified the strings of the notification are updated as the spec. @ivantw08 pls help put a video of your device so we can check as well.
2. however, I notice there is no thumbnail in the notification, confirmed with Roger this can be added in the future. @ChenMorpheus would you like to submit another issue for tracking in the future?
