### ISSUE TITLE
[Revision] Updated the interaction when users stop ScreenshotGo from notification

### ISSUE THREAD

**Issue by ChenMorpheus** [mozilla-tw/ScreenshotGo#315]
Based on #208, we updated the UX spec to alleviate the possible confusion. The new interaction displays a transition of removing the notification instead of prompting a snack bar. Please find [1.3G](https://mozilla.invisionapp.com/share/24N3MMQB986#/310133911_1-3_Dismiss_FAB-Notification) for reference.

<img width="733" alt="image" src="https://user-images.githubusercontent.com/18019946/46992720-0f51d980-d13e-11e8-987b-196cee0de484.png">

**Comment by ivantw08** [comment]
At the version 1.0(549) still show the snack bar as #208.

https://drive.google.com/file/d/1BGzhccZPl-HPymXrFOHHeyZxGr57XCPy/view

**Comment by weslyhuang** [comment]
verified with build 570 nightly + Pixel XL, Android 9.
