### ISSUE TITLE
[Revision] Added the rule for default position and transition of Go button

### ISSUE THREAD

**Issue by ChenMorpheus** [mozilla-tw/ScreenshotGo#316]
We noticed participants couldn't find Go button which overlapped with the screenshot in quick access. I updated the spec for the default position of Go button and @fangshih will provide the transition to introduce the appearance of Go button. Please find [7.1I](https://mozilla.invisionapp.com/share/24N3MMQB986#/310133929_7-1_Onboarding) for details.

<img width="571" alt="image" src="https://user-images.githubusercontent.com/18019946/46992872-d9f9bb80-d13e-11e8-805c-ea05f8490dfe.png">

**Comment by fangshih** [comment]
Here are the two transition proposals for the reference as we've discussed offline. 
https://drive.google.com/open?id=1HbHDA-6JVRh7dQigTDWY0ea-qvWmR39H

**Comment by weslyhuang** [comment]
FAB icon adjustment is done in production beta, others not yet so keep this open.

**Comment by weslyhuang** [comment]
per dicussion, we'll use #397 to investigate this, thus close for now. @elin-moco feel free to reopen it if needed. Thanks.
