### ISSUE TITLE
Collection order on the sorting panel will dynamically be changed each time the user select a collection

### ISSUE THREAD

**Issue by pharspher** [mozilla-tw/ScreenshotGo#320]
**Symptom**
The collection order changed each time the user selects a collection, so the user has to repeatedly go through the whole list to find the target collection when in multi-sorting mode

**Expected**
The collection order should be static at least during the sorting process, making it easier to find the target item

**Comment by pharspher** [comment]
**Root cause** 
Categorizing a screenshot to a collection will update the "date" field of the collection, which is also being used to decide the collection order displayed on the sorting panel and home view.

We've discussed this with the UX designer, @ChenMorpheus please help to comment on this issue, thank you.

**Comment by ChenMorpheus** [comment]
Considering the balance of practicability and effort, we can eliminate the root cause of several bugs by removing the "last edit" column in the dialogue of collection info. I'll update the UX accordingly.
