### ISSUE TITLE
Doesn't prompt a permission to capture everything. (currently only seen in Redmi 4X)

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/ScreenshotGo#324]
**Describe the bug**
Doesn't  prompt a permission to capture everything when hit FAB for the first time.

**Steps To Reproduce**
1. Launch ScreenshotGo with FAB (on)
2. Hit the FAB for the first time

**Expected behavior**
Prompts a permission to capture everything
**Actual behavior**
take screenshot without asking

**Screenshots/videos**
https://drive.google.com/open?id=1KmoFI3Dx6ePiI3D6YhAv3XwARdhkNP8s

**Device info (please complete the following information):**
- Device:Redmi 4X
- OS: Android: 7.1.2
- Version 1.0(505).nightly

Only this device has this issue.

**Comment by weslyhuang** [comment]
clean install?

**Comment by ivantw08** [comment]
@weslyhuang  I installed the version 1.0(549). It doesn't have this issue.

**Comment by weslyhuang** [comment]
@ivantw08 would you help:

1. verify again that this issue still happens in build 505, but not 549?
2. if really fixed in build 549, then restest TC 64~68 and update in the test record file (e.g., add words like "retest with build 549 and pass", ...)

**Comment by ivantw08** [comment]
Both version is working now. I also check TC 64~68. They are passed.

**Comment by ivantw08** [comment]
There is a issue found. When we click the clear data. It should clear all data in the app. So app will act like at initial status. 
issue:
I gave the permission at the first time, Then I clear data. App doesn't prompt anymore.

**Comment by weslyhuang** [comment]
need to check with RD if this is still a valid issue during the next triage

**Comment by weslyhuang** [comment]
confirmed OEM may customize permission storing mechanism so it could be the case that "clear data from system != reinstall". non-actionable thus invalid it.
