### ISSUE TITLE
Screenshot takes much time in desktop

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/ScreenshotGo#326]
**Describe the bug**
The response time of taking screenshot  in the app and desktop are different. 
 
**Steps To Reproduce**

1. Tap FAB in the app (any app)
2. Tap FAB in the desktop 

**Expected behavior**
take same time response in screenshot
**Actual behavior**
take much time in desktop 

**Screenshots/videos**
https://drive.google.com/open?id=1Ft7uLE2W7jRYnqV3y-o7Hyu_d3Z4y6Pp

**Device info (please complete the following information):**
- Device:Advan i5C, Nexus 5 , Redmi 4X
- OS: Android: 6.0.1, Android: 5.1 ,Android: 7.1.2
- Version 1.0(505).nightly

**Comment by ivantw08** [comment]
#61 have the same issue

**Comment by weslyhuang** [comment]
should be same as #61, @benjamin-cheng guess this can be fixed since we've confirmed to hold the permission in the current App life-cycle?

**Comment by weslyhuang** [comment]
confirmed with the team it's the same as #61, which contains more investigation detail so we'll dup (&close) this one.
