### ISSUE TITLE
Remove Go buttom image from unsorted reminder panel

### ISSUE THREAD

**Issue by fangshih** [mozilla-tw/ScreenshotGo#327]
Remove Go buttom image for the unsorted screenshots panel, Thanks
![screenshot_20181018-160331](https://user-images.githubusercontent.com/4862573/47144262-a9aa4c80-d2f9-11e8-91d8-79ce35d94161.png)

**Comment by weslyhuang** [comment]
maybe not really confuse the user, but indeed redundant?

**Comment by weslyhuang** [comment]
verified on my S8+, android 8.0.0 with build 603.
