### ISSUE TITLE
GO button disappeard after system home button clicked

### ISSUE THREAD

**Issue by elin-moco** [mozilla-tw/ScreenshotGo#331]
STR:
1. Open Scryer Nightly
2. Click System Home button
3. Click GO button right away within a few seconds
4. GO button will disappear and the permission prompt will delay longer than usual
5. If we open another app before the permission prompt shows up, the GO button and permission prompt won't ever appear until we found and clicked on the invisible GO button on the screen.

**Comment by weslyhuang** [comment]
step#1~#4 seems to be the known limitation due to getting permission from the system? but unsure about step#5.

**Comment by weslyhuang** [comment]
Dev to do some test about step#5 to see if it's 100% repro, and if anything we can improve...

**Comment by weslyhuang** [comment]
doubt if this issue still exists as we've modified some flow about this. QAwanted.

**Comment by witsmo** [comment]
Verify resolved: ScreenshotGo
Version 1.0 (788)
Device: Samsung S8 Android 8
