### ISSUE TITLE
wired image action 

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/ScreenshotGo#332]
**Describe the bug**
wired image action 

**Steps To Reproduce**
1.Make 5 collections at home page. 
2.Swipe up.
3.Click the image at quick access. 

**Screenshots/videos**
https://drive.google.com/file/d/1yNl0n1tMQQ1HeZfLm9UAv-jb5c9aetHs/view

All device have this issue.

**Comment by weslyhuang** [comment]
tried with my s8+ (18.5:9 display) and I need more than 5 collections to repro this issue. The key seems to be we need enough collections to create "the need of scroll" so the screenshots in quick access will be covered by the search bar.

**Comment by weslyhuang** [comment]
limitation due to Android behavior + current design, need to figure out possible improvement.
