### ISSUE TITLE
https:// recognized as https:/l

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla-tw/ScreenshotGo#340]
In *some* of my screenshots URLs in the Firefox Nightly URL bar starting with `https://` are recognized as `https:/l` which makes it quite hard to just copy/paste it.

![photo5363988045159836067](https://user-images.githubusercontent.com/330324/47291312-702c5680-d603-11e8-844b-8c3989b88ade.jpg)

**Comment by weslyhuang** [comment]
Thanks for the sharing, Michael! We leverage MLKit for OCR so sadly can't just simply fix it, but the team do consider it as a common case so would like to investigate possible improvement in the future (keep this in the product backlog). Feel free to give us a suggestion if any! Thanks again!
