### ISSUE TITLE
ScreenshotGo folder v.s Screenshot folder in Gallery app

### ISSUE THREAD

**Issue by ChenMorpheus** [mozilla-tw/ScreenshotGo#351]
Based on the usability testing and user feedback, users mentioned that they could only access the screenshots in our app instead of finding in the screenshot folder in the Gallery app. The truth is, ScreenshotGo creates its own folder in the Gallery app, and that's why users couldn't find our screenshots in the default screenshot folder. (see attached) We might need to decide if we could simply save the screenshots created by ScreenshotGo to the default screenshot folder to prevent any confusions. @chloechen1122 What do you think?

<img width="706" alt="image" src="https://user-images.githubusercontent.com/18019946/47781882-c4d57d00-dd39-11e8-8137-b136942bed3b.png">

**Comment by weslyhuang** [comment]
support the idea but unsure about the feasibility to correctly identify devices' own screenshot folders (customized by phone manufactures? also will the folder name be localized?). Is it something we can understand by adding telemetry?
