### ISSUE TITLE
[Google Play Feedback] Black Photo

### ISSUE THREAD

**Issue by chloechen1122** [mozilla-tw/ScreenshotGo#352]
Dana SW
Nov 2, 2018 at 8:48 AM
"just black photo" 
Device: Moto G (5S) Plus (sanders_n)
App version: 606 (0.8(606))
OS: Android 7.1 

I'll also ask the user's using scenarios and keep the team updated.

**Comment by mxlius** [comment]
Which app does the user trying to screenshot?
Firefox Focus also has the feature to make the app window secure, not able to be captured, and the symptom matches to expectation.
Follow up action could be updating app description to inform users of this limitation.

**Comment by weslyhuang** [comment]
replied in play console, monitoring for 2 weeks before next action.

**Comment by weslyhuang** [comment]
no feedback and currently non-actionable thus close.
