### ISSUE TITLE
Update OCR button icon 

### ISSUE THREAD

**Issue by fangshih** [mozilla-tw/ScreenshotGo#356]
The OCR icon has new look now. 
<img width="407" alt="screen shot 2018-11-05 at 3 11 29 pm" src="https://user-images.githubusercontent.com/4862573/47983201-8232ec80-e10d-11e8-9a91-084cbde02df1.png">
<img width="84" alt="screen shot 2018-11-05 at 3 11 54 pm" src="https://user-images.githubusercontent.com/4862573/47983204-83641980-e10d-11e8-8062-733cf127a8c2.png">
Assets link: https://drive.google.com/file/d/1NpOVvKcj1btrC6GJcCp0GqRVEOUr9bxw/view
Spec link: https://mozilla.invisionapp.com/d/main/#/console/15016762/313285124/preview

**Comment by pharspher** [comment]
already fixed in #350

**Comment by witsmo** [comment]
Verify resolved on ScreenshootGo 1.0(767)
Device: Nexus 5
OS: Android 6.0.1
