### ISSUE TITLE
Update notification icon 

### ISSUE THREAD

**Issue by fangshih** [mozilla-tw/ScreenshotGo#357]
Currently, we are using the same notification icon for both take shot and sort shot, it's hard to recognize at a glance, so besides updating the string, we also want to use a different icon for the sort shot notification. Thanks!
<img width="569" alt="new notification icon" src="https://user-images.githubusercontent.com/4862573/47983674-ffab2c80-e10e-11e8-917c-fb09ab77e7db.png">

Icon asset: https://drive.google.com/open?id=12K7gKp5lfiTf70Aap1ozuJ-9-xdQWvfm
Spec: https://mozilla.invisionapp.com/share/CQNB9INNKDX#/320477819_9-1_Spec_SP_Empty_Status_Copy

**Comment by witsmo** [comment]
Verify resolved on ScreenshootGo 1.0(767)
Device: Nexus 5
OS: Android 6.0.1
