### ISSUE TITLE
Singular noun with a "s"

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/ScreenshotGo#359]
Steps To Reproduce
1. Take a screenshot 
2. Sort the screenshot to a empty collection (ex. shopping)
3. Go to the collection (ex. shopping)

**Expected behavior**
Show "1 shots" 

**Actual behavior**
Show "1 shot"

Screenshots/videos
https://drive.google.com/open?id=1wIowECl8jNM9dYPMV9jW_WeT98J0Tief

**Device**
Device:Redmi 4X
OS: Android: 7.1.2
Version 1.0(611).nightly
(This happened in all device)

**Comment by weslyhuang** [comment]
maybe minor "visual" impact so S2?
