### ISSUE TITLE
Collection's search icon doesn't match with spec

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/ScreenshotGo#360]
**Description**
There is a search icon in the collection page. But I don't see any search icon in the spec. 

**Steps To Reproduce**
1. Launch ScreenshotGo app
2. Tap a collection 

**Screenshots/videos**
https://drive.google.com/open?id=1wIowECl8jNM9dYPMV9jW_WeT98J0Tief

**spec:**
3.4 : https://mozilla.invisionapp.com/share/CQNB9INNKDX#/screens/313285125
3.1 :　https://mozilla.invisionapp.com/share/24N3MMQB986#/screens/310133919

**Device**
Device:Redmi 4X
OS: Android: 7.1.2
Version 1.0(611).nightly
(This happened in all device)

**Comment by weslyhuang** [comment]
@ChenMorpheus would you help check if we need to update the UX spec, or it's a valid issue? Thanks.

**Comment by ChenMorpheus** [comment]
@weslyhuang Sorry that I didn't put the update in the release note. Yes, it's a valid bug. I decided to remove the "search" icon in all collection page to alleviate the distraction since the "search" icon only provides a quick survey.
