### ISSUE TITLE
 Collection Info without "Last edit time"

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/ScreenshotGo#361]
**Steps To Reproduce**
1. Launch ScreenshotGo
2. Long press a collection
3. Tap Collection Info

**Excepted result**
Show Collection Info (Name, Total screenshots, Storage used, and Last edit time)

**Actual result**
Show Collection Info (Name, Total screenshots, Storage used)

**screenshot**
https://drive.google.com/open?id=1UBjqA2NF_0RYrOkWz9qKHkOkLKQg6VQI

**Device**
Device:Redmi 4X
OS: Android: 7.1.2
Version 1.0(611).nightly
(This happened in all device)

**Comment by ChenMorpheus** [comment]
@weslyhuang Yes, all "last edit" items have been removed. I'll update the UX spec accordingly. Thanks.

**Comment by weslyhuang** [comment]
thanks, TC#21 and #31 are updated accordingly.

https://docs.google.com/spreadsheets/d/1wqMwemaY1dPN710suV7yRG1MqBp85UExFU9iNjA7jqQ/edit#gid=1814723550
