### ISSUE TITLE
Singular noun with a "s" when delete a collection

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/ScreenshotGo#362]
**Description**
 Delete a collection which have only 1 screenshot or 0 screenshot. 

**Excepted result**
0 screenshots, 1 screenshots
**Actual result**
0 screenshot, 1 screenshot

**Screenshots**
https://drive.google.com/open?id=1B-t_wJF-CA7ydCaBCxO-UZaotlD3u6CU
https://drive.google.com/open?id=1rrvXb2mU3ZG1I1nVwj9hyCMPw1XllNu8

**Device**
Device:Redmi 4X
OS: Android: 7.1.2
Version 1.0(611).nightly
(This happened in all device)

**Comment by weslyhuang** [comment]
maybe minor "visual" impact so S2?
