### ISSUE TITLE
Prompt for feedback/share some time after install

### ISSUE THREAD

**Issue by elin-moco** [mozilla-tw/ScreenshotGo#364]
So that we can get sufficient feedback and get to know the share conversion rate.
Currently only 13 feedback in the survey.

**Comment by weslyhuang** [comment]
like Rocket, need a flow for notifying user to give feedback.

**Comment by elin-moco** [comment]
We'll take a look

**Comment by ChenMorpheus** [comment]
@pharspher You can find the attached links for copy and assets, thanks.

Copy: 
https://docs.google.com/spreadsheets/d/1NHL3Yihhb2R3Y2iH4Wm1DiZ_gZfuUq_oz0-kunBwo1I/edit#gid=577733182

Assets:
mdpi https://drive.google.com/file/d/11yccebQsBIUaTztHtO4twf4mCMddFB7a/view?usp=sharing
xxhdpi https://drive.google.com/file/d/11tIhXo1ScVlJux6RfHdMCAkxXMvIxSVP/view?usp=sharing

**Comment by witsmo** [comment]
Verify resolved on ScreenshootGo 0.8(787)
Device: Nexus 5
OS: Android 6.0.1
