### ISSUE TITLE
Figure out what happened to users granted storage permission more than twice

### ISSUE THREAD

**Issue by elin-moco** [mozilla-tw/ScreenshotGo#366]
I listed out devices with the issue, maybe this can help finding out the root cause.
https://docs.google.com/spreadsheets/d/1f8_Yb6OXO6-Q8-TAqgj46Au61LCUfLB-cOxepWVviF4/edit#gid=1148925325

**Comment by weslyhuang** [comment]
agreed during grooming it's critical to resolve this situation.

**Comment by elin-moco** [comment]
@weslyhuang @mxlius @benjamin-cheng 

Currently found strange usage flow when granting storage permission:
Foreground -> Visit welcome page -> Grant storage permission -> Background -> Foreground -> Visit welcome page -> Prompt overlay permission -> Grant storage permission
https://sql.telemetry.mozilla.org/queries/59995

Android 23 (6.0) has most issue rate and most issue devices:
https://sql.telemetry.mozilla.org/queries/59993#155026
https://sql.telemetry.mozilla.org/queries/59993#155022

Around half of Android 23 devices went wrong:
https://docs.google.com/spreadsheets/d/1hMpRJ8sFkhLytbz4ohHfkNc1yeUN9sK1uuKCfMqfkKk/edit#gid=1148925325

This is all I can do for now, let me know if need anything else.

**Comment by benjamin-cheng** [comment]
It seems issue #407 has the reproduce steps for this issue. I can reproduce the same telemetry pattern on firebase and will be fixed in the following PR.

![screen shot 2018-11-14 at 11 55 15 am](https://user-images.githubusercontent.com/7045016/48471082-0e3fc500-e82e-11e8-8355-4bc46723093e.png)
