### ISSUE TITLE
Tracking the event of disabling ScreenshotGo service via notification (Figure out if anything missing when tracking capture service status)

### ISSUE THREAD

**Issue by elin-moco** [mozilla-tw/ScreenshotGo#367]
Currently only tracked 3% turned off capture service.
But the hardware key and other metrics doesn't look like so.
https://sql.telemetry.mozilla.org/queries/59270#153389

@benjamin-cheng 
Did we track when user turn off capture service from persistent notification?

And any other possibility that we will/won't be able to track? force stop? Uninstall? Notification bar?

**Comment by weslyhuang** [comment]
should be P0 I believe.

**Comment by elin-moco** [comment]
@benjamin-cheng 
Question: can we track when user disabled capture service from persistence notification?
If not, can we direct them to settings so that we can track?

**Comment by weslyhuang** [comment]
per discussion, for this issue, the action is: to implement telemetry to track the event of "stopping ScreenshotGo service via notification". @elin-moco would you help confirm, or correct if my understanding is wrong? Thanks.

**Comment by benjamin-cheng** [comment]
Implement the tracking for stopping capture service via notification in #422
