### ISSUE TITLE
No onboarding screen after I uninstall and reinstall ScreenshotGo

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/ScreenshotGo#372]
This was the screen I saw on my Pixel Android 9.0
https://drive.google.com/file/d/1PUhHsBmS8-YPGuHeyrdvizWJDE2YStim/view?usp=sharing

I need to clear storage to see onboarding screen

**Comment by joechengla** [comment]
given this bug, if i see the attached screen as the first screen when i enter the app, i feel the screen is missing some context to explain to me why i need to grant storage permission

**Comment by weslyhuang** [comment]
we may want to enhance this together with #373

**Comment by weslyhuang** [comment]
a bug or a feature request? qa wanted

**Comment by mxlius** [comment]
This is probably caused by android autobackup feature since android 6.0.
https://stackoverflow.com/questions/33169618/an-android-app-remembers-its-data-after-uninstall-and-reinstall

We can try a simple patch to not to preserve onboarding saw flag to make the onboarding screen always appear

**Comment by weslyhuang** [comment]
more like a feature per comment above

**Comment by weslyhuang** [comment]
dup to #373.
