### ISSUE TITLE
Suggestion: More Context to explain why user should grant storage permission

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/ScreenshotGo#373]
https://drive.google.com/file/d/1w2AHqxJOVw6mf0G1Av4rB8_DJc1547xh/view?usp=sharing

if i deny storage permission, every time i come back to the app, i see the attached screen. 
Users may come back days after the first time they deny the permission, if we could provide more context and benefits to the users, it should help users to decide if they want to grant the permissions.

**Comment by weslyhuang** [comment]
question: any data to justify the need of modifying the msg?

**Comment by ChenMorpheus** [comment]
Sorry that I thought the denied state seemed to be irreversible. However, per talked in the meeting yesterday, the denied state can be reversed. As a result, we could simply stop recording the flag of denied state and prompt welcome page instead when users kill the process and revisit the app.

Find 7.1G for spec.

https://mozilla.invisionapp.com/share/24N3MMQB986#/310133929_7-1_Onboarding

<img width="285" alt="image" src="https://user-images.githubusercontent.com/18019946/49196122-a6a87e80-f3c4-11e8-901e-74dc0803175f.png">
