### ISSUE TITLE
Feature Request - Add option to export collections

### ISSUE THREAD

**Issue by OliverParoczai** [mozilla-tw/ScreenshotGo#377]

**Comment by Olika120** [comment]
Hey, thanks for the reply. For example, when you get a new phone and want to export collections and/or screenshots to the new phone. Or you want to build a development build of the app with a different signature that cannot be installed until you uninstall the old app and thus removing every collection you have.

**Comment by weslyhuang** [comment]
Thank you, Olika120. It's more clear to me now about this requirement, we'll bring this to our feature grooming for prioritization and corresponding planning. Thanks again!
