### ISSUE TITLE
The screenshot thumbnail disappeared sometime

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#38]
1. Launch Scryer
2. Tap a collection
3. Quickly tap a shot many times 
4. Quickly tap system Back key many times 
5. Repeat step 3 ~ 4

Expected 
 - The screenshot thumbnail should not disappear

Actual result:
 - The screenshot thumbnail disappeared
 - Video: https://drive.google.com/open?id=1px3yQPoGLYMamZXYGndW8AXo9jiutW1y

Reproduce rate: 1/10

Pixel2 
Android 8.1.0

**Comment by weslyhuang** [comment]
works for me, maybe hard to repro? need to triage but guess S2 may be fair enough.

Android 8.0.0
S8+
