### ISSUE TITLE
Improve view screenshot conversion

### ISSUE THREAD

**Issue by elin-moco** [mozilla-tw/ScreenshotGo#386]
As per discussion with Cloe/Joe,

Users saw home page 72%
Users who viewed screenshot 28%
https://sql.telemetry.mozilla.org/queries/58744#152291
which means view screenshot conversion rate is 38.88%.

Wonder if there's a way that we can improve this conversion? (so more users may get to OCR/share)
e.g. adding a dot/number on category for newly sorted screenshots.

**Comment by weslyhuang** [comment]
should be a feature-backlog that need a joint work (Product, UX, Dev, ...)
