### ISSUE TITLE
Improving sorting conversion rate (lower cancel rate)

### ISSUE THREAD

**Issue by elin-moco** [mozilla-tw/ScreenshotGo#387]
As per discussion with Cloe/Joe.

72% users visited Home page.
Prompt sorting page users 20%, 17% sorted, but 26% cancelled sorting:
https://sql.telemetry.mozilla.org/queries/58744#152291
which means the sort screenshot conversion is 23.61%
and cancel rate is higher (why?)

How can we improve the sorting funnel, so that more users get to the next level of the funnel: view screenshot -> OCR?

**Comment by weslyhuang** [comment]
feature backlog instead of issue for triage.

**Comment by elin-moco** [comment]
Get latest date with single/multiple

**Comment by elin-moco** [comment]
Updated latest data here:

Single: 
 - Cancelled users: 27%
 - Prompted users: 42%
 - Cancel rate: 64.28%
Multiple: 
 - Cancelled users: 16%
 - Prompted users: 28%
 - Cancel rate: 57.14%
