### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#40]
1. Enable FAB
2. Quickly tap FAB 3+ times

Expected
 - no crash

Actual result: 
 -  crash
 - Video: https://drive.google.com/open?id=1c4zvvO_tmnsQ8UjYGy9bFbk0fxd6-NKK

Scryer 1.0 (154).debug
Pixel 2
Android 8.1.0

**Comment by weslyhuang** [comment]
same here with build#160, not necessarily the 3rd tap for me, something need more taps.

**Comment by cynthiatang** [comment]
Verified: Fixed
Pixel 2 
Android 8.1.0
Screenshot 0.8(445)
