### ISSUE TITLE
 Wired selection "select(L10N)".

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/ScreenshotGo#400]
**Description**
There is selection showed "select(L10N)" in every collection's menu.

**Reproduce steps**
1. Launch screenshot
2. Tap any collection
3. Tap menu Right-Top corner

**Screenshot**
https://drive.google.com/open?id=1zhpw9AP940rA4ExwVQJZTqkyyC0mHqyk

**Device&Version**

- ScreenshotGo
- Version 1.0(639)
- Nexus 5 (6.0.1)

**Comment by weslyhuang** [comment]
Thanks Morpheus, @benjamin-cheng would you help patch this in the coming RC? tks~

**Comment by weslyhuang** [comment]
verified pass with RC build 651, Redmi 4X Android 7.
