### ISSUE TITLE
New OCR flow

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/ScreenshotGo#403]

**Comment by weslyhuang** [comment]
@ChenMorpheus we may need to start this with some design ideas, tks.

**Comment by weslyhuang** [comment]
could be only "breakdown + minimum feature" for Sprint#2.

**Comment by benjamin-cheng** [comment]
Confirmed with @ChenMorpheus, the MVP scope would be OCR flow refinement and pan & zoom in detail page. (Pan & zoom in text mode is not included in this scope)
 
1. Basic OCR flow (20 days)
   
   Text highlight (7)
   * Draw highlight text area (3)
   * Handle touch events (2)

   BottomSheet (5)
   * Layout (2)
   * Drag behavior (3)
  
   Custom text selection popup menu (7)
   * Disable system popup menu (2)
   * Menu layout/position (2)
   * Action buttons (2)
     * Web search
     * Copy
     * Share
   * Telemetry (1)

   Overflow menu (1)
   * View full text (1)

2. Pan and zoom in detail page (5 days)

    Integrate the library with pan and zoom feature (5)

**Comment by weslyhuang** [comment]
This issue is for DEV study and breakdown. The outcome is:

1. Basic OCR flow (18 days)

Text highlight (5): #470
BottomSheet (5): #471
Custom text selection popup menu (7): #472
Overflow menu (1): #473

2. Pan and zoom in detail page (5 days): #363

**Comment by elin-moco** [comment]
Just found that this may involve some new telemetry pings, will update later

**Comment by elin-moco** [comment]
Here is the ticket for new OCR flow tracking:
https://github.com/mozilla-tw/ScreenshotGo/issues/516
