### ISSUE TITLE
Stop app via notification without transition 

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/ScreenshotGo#406]
In sepc 1.3G
https://mozilla.invisionapp.com/share/24N3MMQB986#/screens/310133911

Information said that "The notification leaves with a transition to emphasize the action of dismiss."
But there is no transition effect when tapping Stop.

**Device**
ScreenshotGo
Version 1.0(644)
Nexus 5 (6.0.1)

**Comment by weslyhuang** [comment]
@ChenMorpheus I forget if we've discussed this before, the transition effect seems not obvious enough, is this a limitation, or complies the design (your expectation)? tks.

**Comment by weslyhuang** [comment]
visual impact, S2 or lower

**Comment by ChenMorpheus** [comment]
@ivantw08 @weslyhuang Sorry that the definition of transition in the UX spec seems not clear. The transition means that the notification disappears with the native transition when stopped. As a result, it's implemented in the current build. Let me know if any questions, thanks.

**Comment by weslyhuang** [comment]
thanks and clear, so we can close this issue accordingly.

**Comment by weslyhuang** [comment]
@ChenMorpheus just an idea, maybe we can consider to slightly adjust the UX spec description so de-emphasize the "transition" part? otherwise it looks like something we should specifically check during testing. thanks!

**Comment by ChenMorpheus** [comment]
@weslyhuang Updated.

**Comment by weslyhuang** [comment]
saw it and thanks.
