### ISSUE TITLE
Need to tap 2 times Let's Go in Android 6

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/ScreenshotGo#407]
In spec 7.1, only have to press one time Let's go to allow/deny permission. But I need to press 2 times in Android 6.
So TCID 57-60  TC failed.

**spec**
https://mozilla.invisionapp.com/share/24N3MMQB986#/screens/310133929

**video**
allow permission video
https://drive.google.com/open?id=1TqloAm2u_myVnzoeeylkUI2qxtxhBLdw
(00:03 and 00:07 page have different content)

deny permission video
https://drive.google.com/open?id=1GPzrfiDLM__GvTDBYizjFFo7XNl3joGt
(Dialog appeared 2 times. Second dialog  showed "never ask again" option. The first time was not  showed. )

**Device**
- ScreenshotGo
- Version 1.0(639&644)
- Nexus 5 (6.0.1)

**Comment by weslyhuang** [comment]
the video above contains some irrelevant steps, just focus on 8s~12s then you can see 2 different 1st onboarding pages. (with LET'S GO)

https://drive.google.com/open?id=1Mvwi4KmvctaqZrcdsQlqCN07Lyeb4gXm
