### ISSUE TITLE
"Move to..." should be moved out of overflow menu only for unsorted screenshots

### ISSUE THREAD

**Issue by ChenMorpheus** [mozilla-tw/ScreenshotGo#408]
Only for all screenshots in the unsorted collection, "Move to..." should be moved out of the overflow menu as a button next to the "share" button in the detail view. You can refer to [4.1](https://mozilla.invisionapp.com/share/24N3MMQB986#/310133921_4-1_Action_Menu) in the UX spec.

<img width="605" alt="image" src="https://user-images.githubusercontent.com/18019946/48405406-2b608f00-e76d-11e8-9483-9be907d5a6e9.png">

**Comment by witsmo** [comment]
Verify resolved on ScreenshootGo 1.0(767)
Device: Nexus 5
OS:  Android 6.0.1
