### ISSUE TITLE
Canceling "move to" from detail view displays incorrect message

### ISSUE THREAD

**Issue by ChenMorpheus** [mozilla-tw/ScreenshotGo#413]
Except screenshots in unsorted collection, canceling the sorting panel triggered by "move to" in the menu of detail view should not display "added to unsorted." It should simply not display any message."

Example:
Canceling "move to" to the screenshot in "Uber" collection displays "added to Unsorted."

![screenshot_1542190069576](https://user-images.githubusercontent.com/18019946/48476507-30d7db00-e83a-11e8-9e8d-96af999ef9e1.jpg) ![screenshot_1542190099259](https://user-images.githubusercontent.com/18019946/48476508-30d7db00-e83a-11e8-8e91-a65aa59918db.jpg)

**Comment by ivantw08** [comment]
verified 
Nexus5 Android6
Firefox 0.8(727)
