### ISSUE TITLE
Black Friday In-App Event

### ISSUE THREAD

**Issue by chloechen1122** [mozilla-tw/ScreenshotGo#414]
By creating in-app event, we want to prolong session time, improve the user experience, and increase retention.

See Event Calendar: https://docs.google.com/spreadsheets/d/1zNJOjfOVqGR0jaQMzFvnDEuRPD6138DyF3_dOixIjzg/edit#gid=0

**Comment by fangshih** [comment]
Here are the illustration assets for Black Friday in-app event
<img width="398" alt="screen shot 2018-11-16 at 4 12 28 pm" src="https://user-images.githubusercontent.com/4862573/48606383-78857080-e9ba-11e8-8942-709f09f81ded.png">

Image assets: https://drive.google.com/drive/u/2/folders/1GaDlbSuGt3vjsXkzbFsWdvjC21fY-PR9
spec here: https://mozilla.invisionapp.com/share/CQNB9INNKDX#/331746242_11-1_Spec_SP_Holiday

**Comment by weslyhuang** [comment]
closed via #417
