### ISSUE TITLE
Christmas In-App Event

### ISSUE THREAD

**Issue by chloechen1122** [mozilla-tw/ScreenshotGo#416]
By creating in-app event, we want to prolong session time, improve the user experience, and increase retention.

See Event Calendar: https://docs.google.com/spreadsheets/d/1zNJOjfOVqGR0jaQMzFvnDEuRPD6138DyF3_dOixIjzg/edit#gid=0

**Comment by chloechen1122** [comment]
Is it okay to move up this Christmas design/development for all-hands?

**Comment by weslyhuang** [comment]
may work with MKT for push notification promotion

**Comment by weslyhuang** [comment]
@ChenMorpheus @fangshih this is now in scope of the build on next Tue (Nov. 27), so will need to design/visual soon (5 working days from Nov. 21~Nov. 27), fyi.
