### ISSUE TITLE
Send user-defined categories to telemetry

### ISSUE THREAD

**Issue by elin-moco** [mozilla-tw/ScreenshotGo#421]
May need this when sort screenshot/click collection/click on collection item

**Comment by weslyhuang** [comment]
@chloechen1122 regarding the PN doc part, would you help discuss it with Legal? tks.

**Comment by chloechen1122** [comment]
Per discussion with legal,  here are the things we can do before we start collecting the data: 

- Notify the users that we will collect the user-defined collections

- Update Privacy Note if this is permanent

- Get UX team involved: whether this can be opt-in or opt-out (Just like Lite, this can also be included in “send usage data" option)

**Comment by chloechen1122** [comment]
Based on the [Firefox/ Data Collection](https://wiki.mozilla.org/Firefox/Data_Collection) and the discussion with Legal on Dec. 20th, this should be the 3rd category and may be eligible for default on data collection, provided there is an opt-out on pre-release period.

- Pre-Release: May be eligible for default on data collection, provided there is an opt-out.
- Release: Default off.

On a case-by-case basis collections may be eligible to be "default on" if mitigations are identified. Mitigations may include UX changes that make users aware of additional risk, technical mechanisms that remove the risk, or a risk assessment done of a case-by-case basis that determines the risk is limited
