### ISSUE TITLE
wrong collection info when reinstall the app

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/ScreenshotGo#426]
step:
1. launch Screenshot Go 
2. take some screenshots via Firefox Lite (save to unsorted collection )
3. reinstall Screenshot Go 
4. see the unsorted collection info

result: 
Total screenshots is 0.
but there are some screenshot in the collection.

video 
https://drive.google.com/open?id=1SAdat2V7B1ITr7n4G2SnOKoOQ7PkFu2U

device:
ScreenshotGo
Version 0.8(688)
Nexus 5 (6.0.1)

**Comment by weslyhuang** [comment]
I can repro similar issue (collection info) by simply reinstall the App with unsorted screenshots, but the collection info. will be correctly updated once launch the App, following the "ask for sorting" dialogue. 

Ivan also confirmed the collection info will be correctly updated later in his test.

**Comment by weslyhuang** [comment]
minor visual impact I believe thus S3, and P2 to me.
