### ISSUE TITLE
The color of "Actions" should be black

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#43]
1. Launch Scryer
2. Long press a shot

Expected:
 -  Black "Action" 
<img width="555" alt="screen shot 2018-09-03 at 11 05 07" src="https://user-images.githubusercontent.com/12458450/44965667-56f31c00-af69-11e8-8ee3-8c4c2f474f58.png">

Actual result:
 - Green "Action" 
![screenshot_20180903-105339](https://user-images.githubusercontent.com/12458450/44965726-c1a45780-af69-11e8-8564-08523d47b702.png)

Scryer 1.0 (154).debug
Pixel 2
Android 8.1.0

**Comment by benjamin-cheng** [comment]
It's the native context menu of Android platform and has different UI design in different OS version.

**Comment by fangshih** [comment]
Is it possible to at least make sure the "action" text is not using primary teal color? Since we use primary teal color on most buttons that can be pressed, it may confuse users.

**Comment by benjamin-cheng** [comment]
I'll try to override the color through style setting.

**Comment by weslyhuang** [comment]
try to remove "action" directly.

**Comment by cynthiatang** [comment]
Verified: Fixed
ScreenshotGo 1.0(484).nightly
Redmi 4A
Android 7
