### ISSUE TITLE
Send notification within 1st day of install before they churn

### ISSUE THREAD

**Issue by chloechen1122** [mozilla-tw/ScreenshotGo#432]
A push notification can serve as a friendly tap on the shoulder to remind users about how awesome we are. An effective re-engagement push notification should entice users to come back to us by reminding exactly why users downloaded the app to begin with.

**Comment by weslyhuang** [comment]
need to be more specific to proceed.

**Comment by chloechen1122** [comment]
May be able to follow Firefox Lite's approach to wake up inactive users (with push message automation).

**Comment by elin-moco** [comment]
Let me update with a more specific title.

Here is the reference bug from Firefox Lite
https://github.com/mozilla-tw/Rocket/issues/1788

Will put some more details later

**Comment by elin-moco** [comment]
We may need to implement 3 remote configs for the notification:
1. of/off
2. delay time (e.g., 20hr later after install)
3. msg
