### ISSUE TITLE
An option to delete the screenshot when sorting

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/ScreenshotGo#434]
Since I'm not sorting every screenshot immediately, to me often when I want to sort them, the screenshot has already served its purpose and can be deleted. It would be handy if there's a delete option when I'm sorting each screenshot into a category.

**Comment by weslyhuang** [comment]
1. sounds like a valid scenario. unsure if we have existing data to measure the need? @elin-moco. 
2. also flag for UX's design reference @ChenMorpheus.

**Comment by ChenMorpheus** [comment]
@weslyhuang I've prepared a solution for @mTwTm's request(see 1.1D). You can find the attached spec for more details flow. Let me know if any questions, thanks.

<img width="1601" alt="image" src="https://user-images.githubusercontent.com/18019946/51966379-4bb80400-24a7-11e9-8803-118bf55f6081.png">

https://mozilla.invisionapp.com/share/24N3MMQB986#/343830314_1-1_Capture_Screenshot_Via_ScreenshotGo

**Comment by mTwTm** [comment]
That's an interesting design!
I'd also like to add what usually happens on my phone:
1. Usually, I still capture screenshots via hardware keys.
2. I'm using a mid-to-low-end device so often the screenshot sorting prompt don't always show. (ScreenshotGo got killed by the system.)
3. I still from time to time open ScreenshotGo, at that moment, a multiple sorting panel is shown.
4. Sometimes one of the screenshots that are unsorted is already used. (Sent to others via social app or I don't need the memo anymore.)
5. I sort them into a "DELETED" category, and later multi-select in that category to delete them.

**Comment by Conjuror** [comment]
remove ux wanted as ux spec is ready

**Comment by weslyhuang** [comment]
P0 as Sprint#7's nice to have.
