### ISSUE TITLE
Go button doesn't show after granting the overlay permission during onboarding

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/ScreenshotGo#446]
seen in my Samsumg S8+ with Anrdoid 8.0.0 (didn't meet this before)
NOT seen in RedMi Note with Android 7.0
NOT seen in Nexus 5 with Android 6.0.1

1. install and launch the app
2. granted the storage permission, then press ok to jump to system overlay permission page
3. grant overlay permission and press system back key
4. no GO button (enter setting, the go button switch is off)

**Comment by witsmo** [comment]
Verify resolved on ScreenshootGo 1.0(767)
Device: Nexus 5
OS: Android 6.0.1

Device: Redmi 4A
OS: Android 7.1.2
