### ISSUE TITLE
Web search in OCR should have a default search engine

### ISSUE THREAD

**Issue by ChenMorpheus** [mozilla-tw/ScreenshotGo#448]
For the new OCR flow, we'll allow users to search selected text on the Internet. However, the current implementation asks for default search provider, which users are not familiar with. As a result, I'm proposing to trigger the default browser with a predefined search engine(see attached), which we could provide users the ability to change in settings. For instance, tapping web search triggers Firefox Lite and open www.google.com with search results.  @chloechen1122 @joechengla This seems to be product call. What do you think?

<img width="718" alt="image" src="https://user-images.githubusercontent.com/18019946/49214387-84812180-f401-11e8-8931-49553ac3af1e.png">

**Comment by chloechen1122** [comment]
Will check with Charles about this.

**Comment by chloechen1122** [comment]
Discussed with Charles earlier today, it seems perfectly feasible to do so. We could put this into our next sprint planning. @ChenMorpheus @weslyhuang

**Comment by ChenMorpheus** [comment]
@weslyhuang It's not included in the current spec. However, since it's agreed from PM and BD, I'll start working on this part asap.

**Comment by weslyhuang** [comment]
is this already done in Sprint#3 release? @ChenMorpheus

**Comment by ChenMorpheus** [comment]
Yes. But noted that the default search engine might vary depending on
locale.


Morpheus Chen                mochen@mozilla.com
Staff Product/UX Designer            +886 2 8786-1100 ext. 291
                                                 +886 952 085 129

**Comment by weslyhuang** [comment]
verified with build#842. (search with Google)
