### ISSUE TITLE
App Name gets truncated under the icon

### ISSUE THREAD

**Issue by chloechen1122** [mozilla-tw/ScreenshotGo#450]
The name of our app which shows up under the icon is truncated as below:

Device: Samsung A8
OS: 8.0.0

![screenshot_1544609213534](https://user-images.githubusercontent.com/43133942/49912971-d11b3100-fec6-11e8-9c8a-7450b818a6e7.jpg)

**Comment by weslyhuang** [comment]
guess it's handled by phone launcher thus unsure if there is anything we can do. (especially we don't have any space between "Screenshot" & "Go".

**Comment by weslyhuang** [comment]
UI impact, S2 so P2 should be enough.
