### ISSUE TITLE
FAB button not showing properly on Mi 8

### ISSUE THREAD

**Issue by chloechen1122** [mozilla-tw/ScreenshotGo#454]
Device: Mi 8
OS: 8.1.0

For newly-installed user on Mi 8: 
1. Grant the storage access
2. Enable GO button
3. Grant the permission of "Permit drawing over the apps"

The FAB button still is not displayed, the user has to go to "setting" to enable the button again.

**Comment by weslyhuang** [comment]
looks the same as #446, maybe it's also fixed by #455, @benjamin-cheng?

**Comment by weslyhuang** [comment]
#446 is verify-fixed, maybe you can double check on your Mi device, too. @chloechen1122?

**Comment by weslyhuang** [comment]
still seen on Ivonne's device. But not reproducible on Red Mi Note 4, Android 7. Maybe OS version related?
