### ISSUE TITLE
"Share" feature enhancement

### ISSUE THREAD

**Issue by chloechen1122** [mozilla-tw/ScreenshotGo#458]
To enhance user experience in a screenshot sharing in ScreenshotGo.

**Comment by ChenMorpheus** [comment]
Per talked, the attached screen contains the solution to multiple requests. We could simply provide the "share" icon in the sorting panel as "hotfix".

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/18019946/51965966-1232c900-24a6-11e9-848a-d87049bbab20.png">

Spec link:
https://mozilla.invisionapp.com/share/24N3MMQB986#/343830314_1-1_Capture_Screenshot_Via_ScreenshotGo
