### ISSUE TITLE
Onboarding for new OCR flow

### ISSUE THREAD

**Issue by ChenMorpheus** [mozilla-tw/ScreenshotGo#459]
We should have a better way to promote the new OCR flow.

**Comment by ChenMorpheus** [comment]
@weslyhuang @pharspher @benjamin-cheng I've updated the UX and visual spec for this issue. Please let me know if any questions, thanks.

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/18019946/50684344-2d015180-1050-11e9-911e-a68e9a25ed3d.png">


UX spec:
https://mozilla.invisionapp.com/share/24N3MMQB986#/339259899_7-4_Contextual_Onboarding

Visual spec:
https://mozilla.invisionapp.com/share/CQNB9INNKDX#/339264035_5-7_Contextual_Onboarding_Spec

Assets:
https://drive.google.com/open?id=1YuJ39sXI-MJ-QzI5YSwdofk12Gw1uCpx&authuser=mochen@mozilla.com

**Comment by weslyhuang** [comment]
Note: only 2 screens in the above comment, but there is one more in the UX spec (7.4-D) for notifying users "connect internet to download the OCR module". Please help include this if feasible (technical & schedule). Thanks.
