### ISSUE TITLE
After tap LATER to skip sorting, does not show a toast message

### ISSUE THREAD

**Issue by witsmo** [mozilla-tw/ScreenshotGo#463]
**Describe the bug**
After tap LATER to skip sorting, does not show a toast message

**Steps To Reproduce**
1.Tap FAB
2.Tap the shot 
3.Tap "Move to"
4.Tap the shot again
5.Tap LATER to skip sorting

**Expected behavior**
Go gack the orginal page with a toast message "Added to Unsorted"

**Actual behavior**
Go gack to the orginal page and does not show a toast message

**Screenshots/videos**
https://drive.google.com/file/d/1LAOryEVrUrSlUqYsGl0E89loVerQuKLn/view?usp=sharing

**Device info (please complete the following information)**:
Device:Nexus 5
OS: Android: 6.0.1
Version 1.0(776).nightly

**Comment by pharspher** [comment]
Fix in #468

**Comment by witsmo** [comment]
Verify resolved on ScreenshootGo 0.8(787)
Device: Nexus 5
OS: Android 6.0.1
