### ISSUE TITLE
OCR - Text mode - copy selected text : Does not show the snack bar

### ISSUE THREAD

**Issue by witsmo** [mozilla-tw/ScreenshotGo#464]
**Describe the bug**
Text mode - copy selected text: Does not show the snack bar

**Steps To Reproduce**
1. Launch ScreenshotGo
2. Tap a shot
3. Tap OCR
4. Long press selects the text
5. Tap COPY

**Expected behavior**
Show snack bar: Copied

**Actual behavior**
Does not show the snack bar

**Screenshots/videos**
https://drive.google.com/file/d/1cOpdaND28ihD0nJH0GUd-hBx3Gz9Rc1Y/view

**Device info (please complete the following information)**:
Device:Nexus 5
OS: Android: 6.0.1
Version 1.0(776).nightly

**Comment by weslyhuang** [comment]
dup to #182

**Comment by weslyhuang** [comment]
verified on buid#842, with Pixel XL, Android 9.

**Comment by witsmo** [comment]
Same issue on Redmi 4A
Device info (please complete the following information):
Device: Redmi 4A
OS: Android 7.1.2
Version 1.0(860).nightly

**Comment by weslyhuang** [comment]
is it due to SDK upgrade? or maybe exist before and just got found today?

**Comment by weslyhuang** [comment]
@witsmo would you help check if this is OS version related, or brand-related? and if this is a regression? (maybe never fixed for Android 7?)

**Comment by witsmo** [comment]
@weslyhuang 
These two devices of actual behavior does not show the snack bar.
Device: Redmi 4A
OS: Android 7.1.2
Version 1.0(#865).nightly & (#639).nightly

Device: Mi Max
OS: Android 7.0
Version 1.0(#865).nightly & (#639).nightly

And I tried on this device is show the snack bar correctly.
Device: Huawei MediaPad
OS: Android 7.0
Version 1.0(#865).nightly & (#639).nightly

**Comment by weslyhuang** [comment]
build#865 test pass with S8+ Android 8, and Pixel XL, Android 9.

**Comment by weslyhuang** [comment]
confirmed with DEV, the snack bar "copied" goes with our own context menu, which won't work with XiaoMi devices, so the test result above meet the expectation. (as a limitation of the current implementation)

**Comment by witsmo** [comment]
Same issue on Redmi 4A
Device: Redmi 4A
OS: Android 7.1.2
Version 1.0(1145).nightly
