### ISSUE TITLE
New OCR flow (3/4): Custom text selection popup menu (7)

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/ScreenshotGo#472]
breakdown of #403, 3rd part of basic OCR flow including:

Disable system popup menu (2)
Menu layout/position (2)
Action buttons (2)
Web search
Copy
Share
Telemetry (1)

**Comment by benjamin-cheng** [comment]
@elin-moco 
Could you help to provide the event name for the bottom context menu(Web search/Copy/Share)?

![screen shot 2018-12-21 at 5 01 07 pm](https://user-images.githubusercontent.com/7045016/50334150-58f5e080-0542-11e9-9e1e-31876fee3b4e.png)

**Comment by elin-moco** [comment]
@benjamin-cheng 
Search from extracted text
Copy extracted text
Share extracted text

Thank you!

**Comment by weslyhuang** [comment]
per latest status, the implementation will be "floating context menu" instead of a fixed one on the bottom.
