### ISSUE TITLE
Can't find screenshot from LINE

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/ScreenshotGo#476]
1. take a screenshot from the status bar
2. skip the sorting by pressing "cancel", the screenshot is moved to "unsorted"
3. try to select that screenshot in LINE chat
4. can't find that screenshot

video: https://drive.google.com/open?id=17J0kdFfyAKjQ5ciAsdzueii0IFRvSgb8

**Comment by weslyhuang** [comment]
Since it's still "CANCEL" (instead of "LATER") in sorting panel I guess this is old version App before we fix the media center scanning issue?

**Comment by benjamin-cheng** [comment]
According to the sorting panel UI in video, the app version is older than build#794. And the fix has been applied after the build# 794. Just close this issue for verification.

**Comment by witsmo** [comment]
Verified on ScreenshootGo 1.0(913).nightly
Device: Nexus 5
OS: Android 6.0.1
