### ISSUE TITLE
"Privacy Notice" & "Your Rights" in "Settings --> About” (ref: Bug 1487436)

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/ScreenshotGo#49]
Per Web Dev team (Eric Renaud & Paul McLanahan) they will create the URL at the time of PN review.

https://www.mozilla.org/privacy/screenshot-go/

We can integrate it first, even it may lead to an empty page (or error page) at this moment.

**Comment by weslyhuang** [comment]
updated the title to include both the "Privacy Notice" & "Your Rights" here. Content of both are provided by Legal.

**Comment by weslyhuang** [comment]
for (2) above, confirmed with Joe we'll follow the way Rocket did so to embed the content directly (not URL). The content is confirmed here for integrate:

https://docs.google.com/document/d/1QMnw09YXCIHLlo-BtFiJ7S5YvdlX6Uz2UJuKE1I3ovE/edit?ts=5b99d64b

(note in the 3rd bullet "{Privacy Notice}[LINK]" is linking to our privacy notice)

**Comment by mika** [comment]
@weslyhuang wrong mika :)

**Comment by weslyhuang** [comment]
sorry I simply pasted the comment from bugzilla, updated : )

**Comment by weslyhuang** [comment]
Per bugzilla discussion we may need to update the in-product URL of PN. keep following.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1487436#c15

**Comment by weslyhuang** [comment]
Confirmed by PM[1] the URL will be: https://www.mozilla.org/privacy/firefox-screenshotgo/

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1487436#c24
