### ISSUE TITLE
[In-app User Survey Feedback] Contextual hint to help users turn off "ask to sort"

### ISSUE THREAD

**Issue by chloechen1122** [mozilla-tw/ScreenshotGo#491]
Top unsatisfied parts from in-app survey:
    - 29.9% think FAB is annoying, 28.6% think sorting prompt annoying

**Comment by ChenMorpheus** [comment]
Per talked in the meeting, I've prepared two solutions for the user feedback, one is a hotfix, another is a more thorough UX. We could have a discussion to prioritize all the action items.

Hotfix
<img width="647" alt="image" src="https://user-images.githubusercontent.com/18019946/51965671-3d68e880-24a5-11e9-97e0-64d41f17118a.png">

Spec link:
https://mozilla.invisionapp.com/share/24N3MMQB986#/343830317_1-4_Show-Hide_FAB_And_Thumbnail

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/18019946/51965584-f67af300-24a4-11e9-855f-9945d1e7d43e.png">

Spec link:
https://mozilla.invisionapp.com/share/24N3MMQB986#/343830319_3-1_Hotfix_For_Annoyed_Sorting_Panel_

**Comment by ChenMorpheus** [comment]
Here I provide the more thorough solution.


<img width="1886" alt="image" src="https://user-images.githubusercontent.com/18019946/51965817-9fc1e900-24a5-11e9-8da5-dd984a30e6f2.png">

Spec link:
https://mozilla.invisionapp.com/share/24N3MMQB986#/343830310_Cover_Enhancements

**Comment by pharspher** [comment]
resolved in #620
