### ISSUE TITLE
It should trigger a sorting penal with a string "Move to" after tapping "Move to ..."

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#50]
1. Launch Scryer
2. Long press a shot
3. Tap "Move to ..." 

Expected result: 
 - It triggers the sorting penal with a string "Move to"

Actual result: 
 - It triggers the sorting penal with a string "Add to"
 - https://drive.google.com/open?id=16TYgurAmY2MLKrW_J2NRTT8v-me0Su2X

Scryer 1.0 (154).debug
Pixel 2
Android 8.1.0

**Comment by weslyhuang** [comment]
Spec 2.3-C, 2nd level menu, S1.
