### ISSUE TITLE
[Meta] Search (the text recognized by OCR)

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/ScreenshotGo#506]
UX spec WIP.

**Comment by weslyhuang** [comment]
UX Spec draft: https://mozilla.invisionapp.com/share/24N3MMQB986#/screens/310133925

**Comment by benjamin-cheng** [comment]
## Task breakdown

### Home (2)
* Search on-boarding (2)

### Search result page (8)
* UI (3)
  * Listing
  * Loading view
  * Indexing view
  * No results  
* Extract common feature from collection view (3) 
  * Context menu
  * Multi-select
* Full text search (2)
  * Integrate FTS feature
  * Database migration

### Background scanning strategy (5)
* Any activity in the foreground
* Charging
* Periodic work

### Detail page (2)
* Search highlight

### Telemetry?

**Comment by elin-moco** [comment]
Questions to answer:
 - Does search work properly?
   - Measure: events/errors/index progress
 - (How) does user adapt to the search? 
   - Measure: Funnels, Conversion rates, Usage Frequency, Retention, Engagement

To answer the questions, we need to be able to track usage in the new OCR flow.

New Events: (category/value {extra})
 - Index progress
 - Click search result {collection, result_size, result_position}

**Comment by weslyhuang** [comment]
### Home (2): #530 
### Search result page (8): #531 
### Background scanning strategy (5): #532
### Detail page (2): #534
### Telemetry?: #533

**Comment by benjamin-cheng** [comment]
Confirm telemetry part is covered by #533. So close this duplicated issue.
