### ISSUE TITLE
detailed view gets black screen with a long screenshot from Firefox lite

### ISSUE THREAD

**Issue by witsmo** [mozilla-tw/ScreenshotGo#507]
Describe the bug
Tap the shot that took via Rocket does not show anything

Steps To Reproduce
1. Take a shot via Firefox lite
2. Launch ScreenshotGo
3. Tap the shot that you just took via Firefox lite

Expected behavior
No matter the width or height. User can see the whole screenshot in Detail view

Actual behavior
Does not show anything

Screenshots/videos
Vidoe:
https://drive.google.com/file/d/16L87feikFJfJ07Wtq6tEhz2kagKvmEG6/view

ADB Issue log:
https://drive.google.com/file/d/1LKYeiWQSxR2WuFeM_vSzr-bMaUtyKZ_M/view?usp=sharing

Device info (please complete the following information):
Device:Nexus 5 / Redmi 4A / LG Phoenix 2
OS: Android 6.0.1 / Android 7.1.2 /  Android 6.0
Version: V0.8 (902)

**Comment by weslyhuang** [comment]
I can repro with Samsung S8+, Android 8.0. 
Not repro with Pixel XL, Android 9.

Unsure if it's OS version dependent.

**Comment by weslyhuang** [comment]
not repro with Redmi Note 4X, Android 7.0.

**Comment by weslyhuang** [comment]
Roger already got a patch for this (with native transitioning), which looks good per EPM and PM's view.

**Comment by pharspher** [comment]
Fix in #511

**Comment by witsmo** [comment]
Verified on ScreenshootGo 1.0(922).nightly
Device: Nexus 5 / Redmi 4A / Samsung S8
OS: Android 6.0.1 / Android 7.1.2 / Android 8.0
