### ISSUE TITLE
inconsistent snackbar message while OCR (with long screenshot from firefox lite)

### ISSUE THREAD

**Issue by witsmo** [mozilla-tw/ScreenshotGo#508]
Describe the bug
Tap a Screenshot that capture at Firefox Lite and select OCR, Sometime show the different snackbar message

Steps To Reproduce
1. Launch [Firefox Lite] and Visit [bukalapak.com]
2. Tap the [Firefox Lite's screenshot button]
3. Launch ScreenshotGo and tap a Screenshot that capture at [Firefox Lite]
4. Tap the [OCR button] 
5. Tap the [OCR button] again

Expected behavior
Show a snackbar : [Something went wrong? Crop the screenshot and retry.]

Actual behavior
1. After do the step3, the screenshot that capture at firefox lite does not show anything
2. After do the step4, it wiil show a snackbar : "Something went wrong? Crop the screenshot and retry.", and do the step 5 again and again, the snackbar will show : "Text recongnition failed"

Screenshots/videos
Video:
https://drive.google.com/file/d/1wVUZaSGl3RSyeguRMQ5q1AFctEkbBn28/view?usp=sharing

ADB Issue log:
https://drive.google.com/file/d/1vu9Qz_GGTUO8K5jlIfzvzXMDN0X7GV42/view?usp=sharing

Device info (please complete the following information):
Device:Nexus 5 / Redmi 4A
OS: Android 6.0.1 / Android 7.1.2
Version: V0.8 (902)

**Comment by weslyhuang** [comment]
is this only happening after following #507?
Or this can happen independently?
QA wanted.

**Comment by witsmo** [comment]
@weslyhuang I tried it on the Pixel XL (Android 9.0) & Nexus 5X (Android 8.0) that can show the screenshot capture from firefox lite and run TCID46 normally. So I think is only happening after following #507

**Comment by weslyhuang** [comment]
Thanks witsmo, then I think S2 is fairly enough for it.

**Comment by pharspher** [comment]
Fix in #511

**Comment by witsmo** [comment]
Verified on ScreenshootGo 1.0(922).nightly
Device: Nexus 5 / Redmi 4A / Samsung S8
OS: Android 6.0.1 / Android 7.1.2 / Android 8.0
