### ISSUE TITLE
should highlight selected (tapped) text block more (e.g., adding shadow or using a different color)

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/ScreenshotGo#512]
per slack message (Jan 16 1:56pm): 

我發現有一個地方我以為之前的做法是有陰影的...沒補的話panel會跟selected text block 融為一體

![image](https://user-images.githubusercontent.com/13250512/51237696-f4e30280-19af-11e9-91d8-afaed3f00586.png)

**Comment by witsmo** [comment]
Verified on ScreenshotGo 1.0 (945).nightly
Device : Nexus 6
OS : Android 6.0.1
