### ISSUE TITLE
swiping down the text panel doesn't collapse the panel to half screen

### ISSUE THREAD

**Issue by witsmo** [mozilla-tw/ScreenshotGo#513]
Describe the bug
After swipe down the text panel, cannot collapse Text Panel to half screen

Steps To Reproduce
1. Lanuch ScreenshotGO and tap any screenshot
2. Tap [OCR button]
3. Tap any [text block] on the shot 
4. Swipe up [Text Panel]
5. Swipe down [Text Panel]

Expected behavior
Collapse [Text Panel]  to half screen

Actual behavior
Cannot collapse [Text Panel]  to half screen

Screenshots/videos
Videos:
https://drive.google.com/file/d/19r_kqgb4a3Z1TwkvfG1aXurDnnM1zmaD/view?usp=sharing

Device info (please complete the following information):
Device:Nexus 5 / Redmi 4A
OS: Android 6.0.1 / Android 7.1.2
Version: V0.8 (902)

**Comment by weslyhuang** [comment]
dismiss all or collapse text panel to half? could be a design decision.

**Comment by benjamin-cheng** [comment]
Confirmed the current behavior is acceptable from UX perspective. Could we lower the priority to P1?

**Comment by weslyhuang** [comment]
like #514, per the latest design, the current behavior is agreed (no highlight), so this issue is invalid now.

But we'll need to update the test case accordingly. thus qa_wanted

**Comment by Conjuror** [comment]
Disable TCID80 & TCID83 accordingly. remove qa wanted
