### ISSUE TITLE
text of selected/tapped text block is not selected/highlighted in the text panel

### ISSUE THREAD

**Issue by witsmo** [mozilla-tw/ScreenshotGo#514]
Describe the bug
Tap any text block on the shot, the text not hightlighted and not show the context menu

Steps To Reproduce
1. Lanuch ScreenshotGO and tap any screenshot
2. Tap [OCR button]
3. Tap any [text block] on the shot

Expected behavior
1 show [Text Panel] with highlighted text (for the text block you just tapped)
2 show [context menu] for the highlighted text

Actual behavior
1 show [Text Panel] but not highlighted text and not show context menu

Screenshots/videos
Videos:
https://drive.google.com/file/d/19r_kqgb4a3Z1TwkvfG1aXurDnnM1zmaD/view?usp=sharing

Device info (please complete the following information):
Device:Nexus 5 / Redmi 4A
OS: Android 6.0.1 / Android 7.1.2
Version: V0.8 (902)

**Comment by weslyhuang** [comment]
per the latest design, the current behavior is agreed (no highlight), so this issue is invalid now.

But we'll need to update the test case accordingly. thus qa_wanted

**Comment by Conjuror** [comment]
test case is updated. remove qa wanted.
