### ISSUE TITLE
after OCR, have another way to bring users to tap the text block

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/ScreenshotGo#517]
looking at the screen after OCR, I get a feeling to tap [Tap text for more options] first, instead of tapping a text block of the shot following the expected UX flow. Is it something we'd like to enhance?

**Comment by ChenMorpheus** [comment]
@weslyhuang @chloechen1122 I've updated the design and provided visual spec on InVison for @pharspher @benjamin-cheng. Let me know if any questions, thanks.

<img width="1711" alt="image" src="https://user-images.githubusercontent.com/18019946/51301245-7c407c80-1a69-11e9-8055-538700a04057.png">

Spec link:
https://mozilla.invisionapp.com/share/CQNB9INNKDX#/336284161_A1-1_Detail_View_spec

**Comment by witsmo** [comment]
Verified on ScreenshotGo 1.0 (945).nightly
Device : Nexus 6
OS : Android 6.0.1
