### ISSUE TITLE
remove the handler of text panel in default state (just after OCR completion)

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/ScreenshotGo#518]
after OCR completion, the text panel is not yet expanded, and should not have any handler at that time. It may mislead users to try swiping up the text panel.

**Comment by weslyhuang** [comment]
S1 as the handler may mislead users to swipe up the text panel.

**Comment by witsmo** [comment]
Verified on ScreenshotGo 1.0 (927).nightly
Device : Nexus 6
OS : Android 6.0.1
