### ISSUE TITLE
Wrong transition of "hiding text block"

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/ScreenshotGo#520]
[STR]
1. OCR a shot and tap a text block to expend the text panel.
2. tab any empty area of the shot to collapse the text panel.

[expect]
text panel collapse to the bottom directly

[actual]
text panel quickly collapses to "the middle of the screen", then falls to the bottom.

**Comment by weslyhuang** [comment]
seems minor visual impact? maybe S2 is enough?

**Comment by witsmo** [comment]
Verified on ScreenshotGo 1.0 (945).nightly
Device : Nexus 6
OS : Android 6.0.1
