### ISSUE TITLE
height of text panel should be based on the amount of text reocgonized

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/ScreenshotGo#521]
OCR a screenshot and tap any text block to expand the text panel, the height of the text panel is fixed now (half-screen), but we expect the height is adaptive according to the amount of the text recognized.

Compare [Spec 1.1-D & 1.1-H](https://mozilla.invisionapp.com/share/24N3MMQB986#/screens/330737030), the height of the text panel is different per the amount of the text.

**Comment by witsmo** [comment]
Verified on ScreenshotGo 1.0 (945).nightly
Device : Nexus 6
OS : Android 6.0.1
