### ISSUE TITLE
Search (1/5): Home

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/ScreenshotGo#530]
Breakdown of the meta #506.
### Home (2)
* Search on-boarding (2)

**Comment by ChenMorpheus** [comment]
Please refer the attached link for visual spec and assets.

<img width="664" alt="image" src="https://user-images.githubusercontent.com/18019946/51526348-1b4fe480-1e6d-11e9-881b-b8c5b10c450a.png">

Visual spec:
https://mozilla.invisionapp.com/share/CQNB9INNKDX#/342235141_A1-1_Search_Onboarding_spec
