### ISSUE TITLE
Search (2/5): Search result page

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/ScreenshotGo#531]
Breakdown of the meta #506.
### Search result page (8)
* UI (3)
  * Listing
  * Loading view
  * Indexing view
  * No results  
* Extract common feature from collection view (3) 
  * Context menu
  * Multi-select
* Full text search (2)
  * Integrate FTS feature
  * Database migration

**Comment by ChenMorpheus** [comment]
Please refer the attached link for visual spec and assets.

<img width="978" alt="image" src="https://user-images.githubusercontent.com/18019946/51526483-6ec23280-1e6d-11e9-994a-5dd529a2949d.png">


Visual spec:
https://mozilla.invisionapp.com/share/CQNB9INNKDX#/342235140_A1-2_Search_Detail_spec
