### ISSUE TITLE
Search (4/5): Telemetry

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/ScreenshotGo#533]
Breakdown of the meta #506.

**Comment by weslyhuang** [comment]
@elin-moco would you help use this issue for "Search" related telemetry requirement? thanks!

**Comment by weslyhuang** [comment]
copied from #506 

Questions to answer:

Does search work properly?
Measure: events/errors/index progress
(How) does user adapt to the search?
Measure: Funnels, Conversion rates, Usage Frequency, Retention, Engagement
To answer the questions, we need to be able to track usage in the new OCR flow.

New Events: (category/value {extra})

Click search result {collection, result_size, result_position, keyword_length, duration}
Updated events:

Start search {index_progress}
Multi-select related tracking will be handled in a separate issue.

**Comment by elin-moco** [comment]
Note that, we'll need to make sure the "Start search" event for adjust will still be sent as expected.
