### ISSUE TITLE
Phone with notch will block some Screenshot Detail View UI

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/ScreenshotGo#538]
on Pixel 3 XL, when in screenshot detailed view, menu and share button is hard to tap as the system notification bar covers half of the 2 buttons 

when you tap the menu, the first option "move to" is blocked by the notch

**Comment by pharspher** [comment]
fix in #519

**Comment by weslyhuang** [comment]
verified with RC build#959, Pixel 3 XL.
