### ISSUE TITLE
FAB button disappears after update

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/ScreenshotGo#546]
Steps To Reproduce

Launch ScreenshotGo and get FAB on screen
1. Get FAB on screen
2. Update ScreenshotGo version from Play Store
3. Observe FAB

Actual behavior
3. After update, FAB is gone and never back to screen

Screenshots/videos
Videos:

Device info (please complete the following information):
Device: Redmi 5 Plus
OS: Android 7.1.2
Version: V0.8 (902)

**Comment by Conjuror** [comment]
video will be updated later.

**Comment by Conjuror** [comment]
If a user turns auto update on and the device update ScreenshotGo on background, the user will simply feel FAB is gone with no reason.

**Comment by weslyhuang** [comment]
@Conjuror just to confirm, after updating and FAB is closed:

A: will the FAB appear again when you launch the app? --> then seems ok for me and P2 at most.

OR

B: the FAB won't be shown even you launch the App (meaning the setting of FAB is also changed) --> maybe P1~P0.

**Comment by Conjuror** [comment]
@weslyhuang it's **A**. I guess it's fine to put to P2 or even P3. Just a reminder to polish the activity when we are heading to official launch. It won't break major behavior now.
