### ISSUE TITLE
Contextual onboarding - When back to the homeview, still show the dot hint

### ISSUE THREAD

**Issue by witsmo** [mozilla-tw/ScreenshotGo#547]
Describe the bug
Contextual onboarding - When back to the homeview, still show the dot hint

Steps To Reproduce
1. Lanuch ScreenshotGo to the [homeview]
2. Tap the [screenshot] with the [dot hint]
3. Tap on [any place] on the screen
4. Back to the [homeview]

Expected behavior
No dot hint on the same screenshot

Actual behavior
Show dot on the same screenshot

Screenshots/videos
https://drive.google.com/file/d/1LCznM9p5HbbHf6wCm1rGphs2niBosrym/view?usp=sharing

Device info (please complete the following information):
Device: Nexus 5 
OS: Android 6.0.1
Version: v0.8 (959)

**Comment by weslyhuang** [comment]
also repro in Pizel XL, Android 9. However it can recover after either "back key to home and enter the app again" or "re-launch the app". So P1 the most.
