### ISSUE TITLE
when relaunch the app, show the screenshots and "No screenshots yet" background

### ISSUE THREAD

**Issue by witsmo** [mozilla-tw/ScreenshotGo#548]
Describe the bug
when relaunch the app, show the screenshots and "No screenshots yet" background

Steps To Reproduce
1. Lanuch ScreenshotGo and take one or two screenshots
2. Tap system back button
3. Relaunch the app

Expected behavior
Show one or two screenshots

Actual behavior
Show one or two screenshot and show "No screenshots yet" background

Screenshots/videos
https://drive.google.com/file/d/1fqTHazavafati6Z6R_QUy1OHrFhsrcoC/view?usp=sharing

Device info (please complete the following information):
Device: Nexus 5 
OS: Android 6.0.1
Version: v0.8 (959)

**Comment by weslyhuang** [comment]
repro in Pixel X, too.

**Comment by weslyhuang** [comment]
verified with Nexus 5, Android 6 with new RC build#969

**Comment by weslyhuang** [comment]
RC2 also verified with Pixel XL, Android 9.

**Comment by weslyhuang** [comment]
fixed by #552
