### ISSUE TITLE
No action when users double tap the FAB 

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#55]
1. Enable FAB
2. Double tap the FAB

Expected result: 
 - Show the window "Scryer will start capturing everything that's displayed on your screen" 

Actual result
 - no action
 - video:  https://drive.google.com/open?id=1_PVrwt0HJnEXVW9-Scq43O3trQ3zr3pb

Scryer 1.0 (160).debug
OPPO A37f
Android 5.1.1

**Comment by weslyhuang** [comment]
same here, in fact the FAB behavior seems a bit unstable for me, delayed screenshot from time to time, and sometimes not work with 1 tap (and the 2nd tap works). 1st nemu so S1 and I believe we should put it P1. too.
