### ISSUE TITLE
A user cannot sort a shot right after scrolling collection list

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/ScreenshotGo#557]
Describe the bug
After scrolling collection list, no response while tapping on a collection 

Steps To Reproduce

1. Tap FAB to take a screenshot and ScreenshotGo requests to sort a shot
2. Scroll the collection list
3. Tap on a collection

Expected behavior
3. Sorted into selected collection and an animation of check mark on selected item

Actual behavior
No response

Screenshots/videos

Device info (please complete the following information):
Device: Redmi 5 Plus
OS: Android 7.1.2
Version: v0.8 (969)

**Comment by weslyhuang** [comment]
indeed can repro on my device but hard to, guess P2 the most.
