### ISSUE TITLE
Unable to select the last line of text in text mode (OCR)

### ISSUE THREAD

**Issue by elin-moco** [mozilla-tw/ScreenshotGo#561]
Device: HTC U-Ultra
STR: 
1. open text mode in a screenshot with multiple lines of text
2. click on one text block with multiple lines
3. try to select the whole text in the block

![screenshot_20190214-120140](https://user-images.githubusercontent.com/3771202/52762039-c9a40f80-3050-11e9-8f6b-991f4ea0e60a.png)

**Comment by weslyhuang** [comment]
Can't repro with Redmi 5 plus, Redmi note 4x, and Pixel XL.
I can sometimes repro with S8+ when the system tray (back, home, menu) is hidden, but unsure if this is the same thing.

P2 first as the impact seems limited for now.
