### ISSUE TITLE
User Feedback: OCR "Tap Text for More Options" 

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/ScreenshotGo#562]
Much improved OCR UX :) Great work
Providing my first impression/reaction feedback.
When I used the updated OCR feature for the first time, I need to think a little bit 

1. Tap text for more options. Not hard to figure out but i think Tap "highlighted" texts could be more clear
2. When I tapped the highlighted text box and the text is now shown in the bottom. I hesitated for longer here as no option was shown to me as per the instruction. I single tapped on the bottom text area first to see if there's any actions, but no, so then I tried long press on the texts to get the options.

FYI

**Comment by weslyhuang** [comment]
tag for UX's notice.
