### ISSUE TITLE
Failed to detect new screenshots when "Prompt to save" is disable 

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#57]
Settings:
 - Enable screenshot service
 - Enable screenshot button (FAB)
 - Disable Prompt to save

STR
1. Tap system Home key
2. Tap the FAB
3. Launch Scryer

Expected result:
 - It should check if there are any unsorted screenshots since the last visit. If yes, it prompts reminder to ask users 

Actual result:
 - It doesn't prompt users about "Unsorted screenshots"
 - Video: https://drive.google.com/open?id=1O9bvK_bpDoZkrgejMU5d7U38K3pgiHi6

Scryer 1.0 (160).debug
All device

**Comment by weslyhuang** [comment]
1st level menu so S, and important enough as P1 I think.

However it works for me with build 175 debug. build 160 seems old, @cynthiatang would you help check if this is still happening in the latest build? tks.

**Comment by cynthiatang** [comment]
Works for me.

ScreenshotGo 1.0(346).nightly
