### ISSUE TITLE
Track % of screenshot that have text in Telemetry 

### ISSUE THREAD

**Issue by elin-moco** [mozilla-tw/ScreenshotGo#583]
As PM (I'm writing on behave of Cloe), I would like to know the % of screenshots in user's device, so that we can determine the impact and priority of text-relevant features.

AC:
1. verified receiving the percentage number on Firebase debugging console
2. make sure we are able to calculate conversion rate in relevant funnels based on the number.

* note that we may need to set a threashold of 10 characters
* If there's concerns regarding performance, maybe we can sent only for the first time (after indexing complete?) for each device.

**Comment by benjamin-cheng** [comment]
@elin-moco could you help to provide the event template(name,...) of this telemetry?

**Comment by elin-moco** [comment]
We should do this like "screenshot_count" in core ping.
The suggested name would be: indexable_screenshots
unit is percentage: 1-100
