### ISSUE TITLE
selecting all screenshots takes time and might cause confusion

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/ScreenshotGo#596]
Step
1. Launch ScreenshotGo
2. Select "VIEW ALL" in Quick access
3. Tap Menu on the upper-right
4. Tap Select
5. Select all screenshots

Expected Result:
5. UI responses or select all screenshots immediately

Actual Result:
5. Screenshots are selected after a period of time

DuT: Redmi 5 plus (Android 8.0)
Build: 1081

**Comment by Conjuror** [comment]
https://drive.google.com/file/d/19zOk9OyU_IoPOiuQEIc3PJblIepQn41y/view?usp=sharing

**Comment by weslyhuang** [comment]
it might be low impact if this issue has existed for a while (and we don't get complained for it). 
Or this is in fact a regression? can we check if this was the same situation in the 1st day when we had multi-select feature?

**Comment by Conjuror** [comment]
build 896 has the same issue. It's not a regression
