### ISSUE TITLE
Screen is black out when opening from search result

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/ScreenshotGo#602]
Description:
Users cannot view an image from search result

Steps:
1. Launch ScreenshotGo
2. Search images
3. Tap an image from search results

Expected Result:
3. The image is opened correctly

Actual Result:
3. The image is all in black.

DuT: Sony Z3C (Android 5.0.1)
Build: 0.8 (1092)

**Comment by Conjuror** [comment]
I am not sure if it's the same problem. I'll follow up if we need more actions (such as open a new issue).

Following above test step:
4. Tap menu on the upper-right
5. Tap on delete to delete the image

Expected Result:
5. Image is deleted (?

Actual Result:
5. App crashes

**Comment by Conjuror** [comment]
Labeled with QAwanted to track if we need open a new issue for it. I believe they are caused the same reason for now.

**Comment by benjamin-cheng** [comment]
https://console.firebase.google.com/u/0/project/ml-kit-codelab-ea3fc/crashlytics/app/android:gro.allizom.scryer/issues/5c7e264ef8b88c2963f4ab0b?time=last-seven-days&sessionId=5C7E26DA006D000144CCD55D21E84657_DNE_0_v2

**Comment by Conjuror** [comment]
Remove QA wanted since it's been fixed.
