### ISSUE TITLE
It is slow to take a screenshot via FAB (Go to Scryer -> back to home screen-> Tap FAB)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#61]
Enable FAB

1. Launch Scryer
2. Tap Home
3. Tap FAB

Actual result:
 - more than 4 seconds to show up 
 - https://drive.google.com/open?id=1pqth3BDTmYRR7DhOncccdUblv1JOCWWe

Pixel2 
Android 8
Scryer 1.0 (158).debug

**Comment by weslyhuang** [comment]
I met this too from time to time in different scenarios. guess this is important enough to be S1 & P1.

**Comment by benjamin-cheng** [comment]
It should be Android framework design/issue to take few seconds to request a capture permission. It can also be reproduced in other screenshot apps. To workaround it, need to keep the capture permission all the time even when user does not check "Don't show again", which violated the expected behavior of the issue #67

**Comment by weslyhuang** [comment]
Joe will discuss with Legal as well.

**Comment by weslyhuang** [comment]
need to revisit to decide if it's P0 or P1, and the design project would like to go.

**Comment by benjamin-cheng** [comment]
It's more like a feature from Google side to protect user from malware. 
https://issuetracker.google.com/issues/36910222

I have verified that it's only impacted when user press home key and would like to take screenshot within 5 seconds. After the 5 seconds, user can take screenshot what he/she wants. Maybe, we could reconsider does it really impact normal user?

**Comment by weslyhuang** [comment]
good to know that and support the idea to re-consider its priority.

**Comment by weslyhuang** [comment]
per standup discussion, maybe not P0 so down to P1 and keep monitoring.

**Comment by weslyhuang** [comment]
reference other App's status. @cynthiatang

**Comment by weslyhuang** [comment]
confirmed should be improved (partially-fixed) since we've confirmed to hold the permission in the current App life-cycle (#240). Though it still takes longer time "in the first capture" due to requesting the permission.

**Comment by weslyhuang** [comment]
please qa help compare this when verifying the fix, and leave comment. tks.

App w/o the fix: 1st-time capture, and the following capture
App w/ the fix: 1st-time capture, and the following capture
