### ISSUE TITLE
Does not show "Don't show again" in start capture permission

### ISSUE THREAD

**Issue by witsmo** [mozilla-tw/ScreenshotGo#610]
Describe the bug
Does not show "Don't show again" in start capture permission

Steps To Reproduce
1. Launch ScreenshotGo with FAB (on)
2. Hit the FAB for the first time

Expected behavior
Select "Don't show again" and tap START NOW

Actual behavior
Does not show "Don't show again" in start capture permission

Screenshots/videos
https://drive.google.com/file/d/1aSHvXlVEngvOlOACbTpfWz4_WRQq5h2c/view?usp=sharing

Device info (please complete the following information):
Device: Redmi 4A
OS: Android 7.1.2
Version: ScreenshotGo v0.8(1106)

**Comment by weslyhuang** [comment]
known issue for certain OEM implementation.
