### ISSUE TITLE
Long press a text in text panel, can't select copy/share in 3-dots button

### ISSUE THREAD

**Issue by witsmo** [mozilla-tw/ScreenshotGo#611]
Describe the bug
Long press a text in text panel, can't select copy/share in 3-dots button

Steps To Reproduce
1. Lanuch ScreenshotGO and tap any screenshot
2. Tap [OCR button]
3. Tap any [text block] on the shot
4. Long press on a text in [Text Panel]
5. Tap [COPY]/[SHARE] on the [Context menu]

Expected behavior
1. For [COPY], show snack bar: [Copied]
2. For [SHARE], prompt [share via panel] 

Actual behavior
Can not select copy/share in 3-dots button

Screenshots/videos
https://drive.google.com/file/d/1BEGj_-i3p2eT_xGsRigRrPevfwrKlFCk/view?usp=sharing

Device info (please complete the following information):
Device: Advan i5C
OS: Android 5.1
Version: ScreenshotGo v0.8(1106)

**Comment by weslyhuang** [comment]
P0 per yesterday's sync with PM & UX.

**Comment by witsmo** [comment]
Verified PASS on ScreenshotGo v0.8 (1113)
Device : Advan i5C
OS : Android 5.1

**Comment by weslyhuang** [comment]
verified pass with my Z3c Android 5.0, too.
