### ISSUE TITLE
When enable screenshot service, does not show the screenshotGo notification(only on Android 8)

### ISSUE THREAD

**Issue by witsmo** [mozilla-tw/ScreenshotGo#614]
Describe the bug
When enable screenshot service, does not show the screenshotGo notification(only on Android 8)

Steps To Reproduce
Precondition:
Enable screenshot service

Step:
1. Launch ScreenshotGo

Expected behavior
Show the FAB and screenshotGo notification

Actual behavior
Show the FAB but not show the screenshotGo notification

Screenshots/videos
https://drive.google.com/file/d/1cOOM2_Ibkt2TkjVhfVOXB3-WdNMMnk5C/view?usp=sharing

Device info (please complete the following information):
Device: Samsung S8
OS: Android 8.0
Version: ScreenshotGo v0.8(1113)

**Comment by weslyhuang** [comment]
@benjamin-cheng I remember this is OEM related limitation (supporting persistent notification or not), right? Thanks.
