### ISSUE TITLE
Unlock screen and take a screenshot immediately when a user double tap the Scryer's notification in screen lock mode

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#62]
Enable screenshot service

1. Press Power key --> screen lock
2. Press Power key again
3. Double tap the Scryer's notification 

Actual result:
 - Unlock screen and take a screenshot immediately 

Expected result:
 - Don't take a screenshot

Pixel2
Android 8.1.0
Scryer 1.0 (158).debug

**Comment by weslyhuang** [comment]
I met this too from time to time in different scenarios. guess this is important enough to be S1 & P1.
