### ISSUE TITLE
Prompt to sort hinter should show once only

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/ScreenshotGo#633]
**Description**
The hinter for dismissing "prompt to sort" is still shown. According to spec, this should show once only.

**Reproduce Step**
Prompt to sort enabled

1. Launch ScreenshotGo
2. Take a screenshot with FAB
3. Tap back key to cancel sorting
4. Repeat step 2 & step 3
5. Tap "ASK TO SORT"
6. Repeat step 2 to step 4

Expected Result:
4. "No more sorting?" hinter is shown
6.  No hinter anymore

Actual Result:
6. Hinter is still shown

Build: 0.8(1145)

**Comment by pharspher** [comment]
Solved in #631
