### ISSUE TITLE
There is no <# of remaning> remaining in the "Skip the rest" dialogue

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#64]
1. Take some screenshots
2. Open Scryer
3. Tap SORT
4. Tap system Back key

Expected Result
 - There is a <# of remaning> remaining in the Skip the rest dialogue (UX spec: 2.4 E)

Actual Result:
 - There is no <# of remaning> remaining in the Skip the rest dialogue
 - ![screenshot_2018-09-04-07-05-54-34](https://user-images.githubusercontent.com/12458450/45028317-27323a00-b077-11e8-9f5e-3257dfba1e46.png)

Scryer 1.0 (160).debug
OPPO A37f
Android 5.1.1

**Comment by weslyhuang** [comment]
still the same with build 210. should belong to the 1st or 2nd level menu so S1.

**Comment by cynthiatang** [comment]
Verified: Fixed

ScreenshotGo 1.0(505).nightly
Sony Z3C
Android 6.0.1

![screenshot_20181009-115756](https://user-images.githubusercontent.com/12458450/46647606-a27d9300-cbc3-11e8-959b-faf3c126157a.png)
