### ISSUE TITLE
The screenshot notification never comes back after it is killed by low memory

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/ScreenshotGo#641]
User impact: The screenshot notification goes away and never comes back.
Technically: The screenshot service is not sticky.

https://github.com/mozilla-tw/ScreenshotGo/blob/master/app/src/main/java/org/mozilla/scryer/ScryerService.kt#L108
When the Service is re-created, we return directly and the service is killed. We should remove the null protection.

**Comment by weslyhuang** [comment]
could be a P1 if we're going to make a new release. @ChenMorpheus @chloechen1122 feel free to comment about the priority if any. Tks.
