### ISSUE TITLE
Automated l10n string merge for Nightly build (like Rocket)

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/ScreenshotGo#65]
1. less manual work.
2. easier for the community to check the latest l10n result on UI.

**Comment by weslyhuang** [comment]
If this can be easily enabled from Rocket's solution, I would propose to be P1.

**Comment by Delphine** [comment]
Thanks! I'm just CCing @flodolo and @gueroJeff so they are aware of this, and in case of updates while I'm on PTO :)
