### ISSUE TITLE
Failed to prompt the sorting panel with 3 items in landscape mode

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#68]
1. Enable FAB
2. Play a video in landscape mode
3. Tap FAB

Expected Result:
 - While users take screenshots in landscape mode, it prompts the sorting panel with 3 items in a row

Actual Result:
 - It prompts a sorting panel with 2 items in Portrait mode 
 - https://drive.google.com/open?id=1TnXgVmCCjjslMRuUr3AbHIiU3SP4JC8V

Scryer 1.0(173).debug
Pixel2
Android 8.1.0

**Comment by weslyhuang** [comment]
UX Spec 8.1D, not complying Spec (1st~2nd level menu), thus S1.
