### ISSUE TITLE
Detail view is not ready for testing

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#71]
1. Launch Scryer
2. Tap a screenshot in Quick access
3. Check the detail view

Expected Result
 - The header is transparent and consists of back, share and overflow menu buttons

Actual Result
 - It's not ready for testing

![screenshot_20180905-143413](https://user-images.githubusercontent.com/12458450/45075612-4504ab00-b11a-11e8-81fd-ae1822d067ca.png)

Scryer 1.0(173).debug
All device

**Comment by weslyhuang** [comment]
MVP of open beta so P1.

**Comment by fangshih** [comment]
Just updated the visual spec for landscape mode and landscape screenshot. The background color will change to black. 
![screen shot 2018-09-10 at 5 35 11 pm](https://user-images.githubusercontent.com/4862573/45289507-e7a89980-b51f-11e8-9d0f-7694f33e3388.png)

**Comment by cynthiatang** [comment]
It is read for testing
