### ISSUE TITLE
App icon in about page

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#74]
1. Launch Scryer
2. Go to Menu ->Settings -> About

Expected result:
 - About page shows the version of the app and other relevant links
 - There is an app icon 
<img width="341" alt="screen shot 2018-09-18 at 10 56 28" src="https://user-images.githubusercontent.com/12458450/45661792-9dcc3e80-bb31-11e8-9d55-08737e38e39a.png">

Actual result:
 - no app icon 
![screenshot_20180918-105347](https://user-images.githubusercontent.com/12458450/45661834-db30cc00-bb31-11e8-92af-2682653c61df.png)

Scryer 1.0(346).nightly
Pixel2
Android 8.1.0

**Comment by weslyhuang** [comment]
MVP of open beta thus P1, also 2nd level menu so S1.

**Comment by weslyhuang** [comment]
@cynthiatang do you think we can close this issue now? Thanks

In the "About" page there are:
1. product name and version --> is it already in the in the current nightly build?
2. Support link --> tracked in #160 
3. Your Rights --> tracked in #49 
4. Privacy Notice --> tracked in #49

**Comment by cynthiatang** [comment]
@weslyhuang , I changed the title for missing app icon in about page

**Comment by weslyhuang** [comment]
thanks and clear!

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixel2 
Android 8.1.0
ScreenshotGo 1.0(454).nightly
