### ISSUE TITLE
No action when users tap GIVE US FEEDBACK

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#75]
1. Launch Scryer
2. Go to Menu -> Settings -> Give feedback

Expected Result
 - When users tap GIVE US FEEDBACK, it would lead users to a survey page  
 
Actual Result
 - No action when users tap GIVE US FEEDBACK
 - Wait for the image 

Scryer 1.0(173).debug
Pixel2
Android 8.1.0

**Comment by weslyhuang** [comment]
2nd level menu = S1
MVP of open beta = P1.

**Comment by benjamin-cheng** [comment]
@joechengla Could you provide the survey the link for Scryer like Rocket? (https://qsurvey.mozilla.com/s3/Firefox-Rocket-3-0-Input/)

**Comment by weslyhuang** [comment]
@elin-moco is the qsurvey link prepared by MArketing team? tks!

**Comment by elin-moco** [comment]
@weslyhuang Chloe will work with marketing team on the survey.

**Comment by elin-moco** [comment]
@weslyhuang @benjamin-cheng 
The survey link is created:
https://qsurvey.mozilla.com/s3/Firefox-ScreenshotGo-Input
Content will be updated once ready.

Thank you!
