### ISSUE TITLE
The status bar at the top of the screen disappears after opening Scryer (OPPO only)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#77]
1. Launch Scryer
2. Check the status bar at the top of the screen

Expected Result
 - The status bar at the top of the screen does not disappear

Actual Result
 - The status bar at the top of the screen disappears
 - Video https://drive.google.com/open?id=1icpu7Rswd0MlZ_1YNlIFwhdRhNruskcI

Scryer 1.0(175).debug
OPPO A37f
Android 5.1.1

**Comment by weslyhuang** [comment]
looks related to the OEM's customized behavior of status bar color? guess S1 but not necessarily P1 (flagging for triage), if only for Oppo.

**Comment by weslyhuang** [comment]
would like to know more devices's result.

**Comment by cynthiatang** [comment]
This issue cannot be reproduced in Redmi 4A, Nexus5, Lenovo 1000m, Samsung J7, Pixel2, Vivo

**Comment by weslyhuang** [comment]
verified with Oppo A3, Android 8.1.0, build#794.
