### ISSUE TITLE
would be nice to stay in previous page when opening app via Notification

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/ScreenshotGo#99]
Enable screenshot service
STR
1. Launch Scryer
2. Tap Settings or open sorting penal
3. Go to Android Home 
4. Expenand Scryer's notification 
5. Tap Open app

Expected 
 - Open Scryer. Scryer will stay in Settings or sorting penal

Actual result 
 - Open Scryer Home

Scryer 1.0(202).nightly
Pixel 2 with Android 8.1.0

**Comment by weslyhuang** [comment]
may need UX input for the best design here. also need to consider if this is doable from tech perspective.
